// provider／budget store 的 PostgreSQL 原生 schema（升級層 D-0021 首包）。
//
// 為什麼需要它：budgetGuardAsync.js 原本靠「SQLite handle 當 schema 來源」鏡射建表＋對齊
// identity 序號（ensurePgSchema / resyncIdentitySequences 都吃 sqliteDb）。正式 PG 模式
// 把 PG_NO_SQLITE_OPEN=1 打開後根本沒有 SQLite handle，所以把**權威 schema 定義搬到 PG 側**。
//
// 欄位型別／可空性／預設值逐欄對齊正式庫 5151_shadow（information_schema.columns /
// pg_indexes / pg_constraint 唯讀實測），SQLite 側的 DDL（budgetGuard.js ensureBudgetSchema）
// 與之同源：INTEGER→BIGINT、TEXT→TEXT、INTEGER PRIMARY KEY AUTOINCREMENT→
// BIGINT GENERATED BY DEFAULT AS IDENTITY。
//
// 這裡刻意補上兩件「SQLite 鏡射」做不到、但 PG 一定要有的事（與 budgetGuardAsync.js 舊註解
// 同一件事）：
//   1. SQLite 的 UNIQUE **表約束**是隱式索引（不在 sqlite_master 裡），pgSchema 鏡射看不到，
//      所以這裡在 CREATE TABLE 用內聯 `UNIQUE(...)` 顯式宣告；同時保留
//      `CREATE UNIQUE INDEX IF NOT EXISTS` 當既有表（legacy 鏡射出來、只有 unique index 沒有
//      constraint 的）遷移後盾，索引名沿用正式庫現有那三個。
//   2. 帶 id 的匯入不會推進 identity 序號 → 初始化時對每張 identity 表
//      setval(pg_get_serial_sequence(...), max(id)+1)。setval 到 max(id)+1 是冪等的：重跑不變、
//      且只在表有 identity 欄時才發（provider_secrets 用 text 主鍵，不在此列）。
import { quoteIdent } from "./pgSchema.js";

const TEXT = "TEXT";
const BIGINT = "BIGINT";
const IDENTITY_ID = `${BIGINT} GENERATED BY DEFAULT AS IDENTITY`;

// 單一來源：每張表的欄位定義。`default` 是原生的 SQL 字面量（例：`"''"`、`"0"`、`"'v1'"`）。
export const BUDGET_PG_TABLES = [
  {
    name: "system_provider_configs",
    identity: "id",
    columns: [
      { name: "id", type: IDENTITY_ID, primaryKey: true },
      { name: "category", type: TEXT, notNull: true },
      { name: "provider_code", type: TEXT, notNull: true },
      { name: "region", type: TEXT, notNull: true, default: "''" },
      { name: "model_id", type: TEXT, notNull: true, default: "''" },
      { name: "endpoint", type: TEXT, notNull: true, default: "''" },
      { name: "is_enabled", type: BIGINT, notNull: true, default: "0" },
      { name: "credential_ref", type: TEXT },
      { name: "price_version", type: TEXT, notNull: true, default: "'v1'" },
      { name: "fallback_policy", type: TEXT },
      { name: "daily_limit_minor", type: BIGINT, notNull: true, default: "0" },
      { name: "monthly_limit_minor", type: BIGINT, notNull: true, default: "0" },
      { name: "ceiling_minor", type: BIGINT, notNull: true, default: "0" },
      { name: "sort_order", type: BIGINT, notNull: true, default: "0" },
      { name: "created_at", type: TEXT, notNull: true },
      { name: "updated_at", type: TEXT, notNull: true },
    ],
    unique: [["category", "provider_code", "region", "model_id"]],
    uniqueIndexes: [{ name: "system_provider_configs_provider_uniq", columns: ["category", "provider_code", "region", "model_id"] }],
    indexes: [],
  },
  {
    name: "provider_secrets",
    identity: null,
    columns: [
      { name: "credential_ref", type: TEXT, primaryKey: true },
      { name: "nonce", type: TEXT, notNull: true },
      { name: "ciphertext", type: TEXT, notNull: true },
      { name: "created_at", type: TEXT, notNull: true },
    ],
    unique: [],
    uniqueIndexes: [],
    indexes: [],
  },
  {
    name: "budget_limits",
    identity: "id",
    columns: [
      { name: "id", type: IDENTITY_ID, primaryKey: true },
      { name: "scope_kind", type: TEXT, notNull: true },
      { name: "scope_key", type: TEXT, notNull: true },
      { name: "period_kind", type: TEXT, notNull: true },
      { name: "period_key", type: TEXT, notNull: true },
      { name: "timezone", type: TEXT, notNull: true, default: "'Asia/Taipei'" },
      { name: "limit_minor", type: BIGINT, notNull: true, default: "0" },
      { name: "settled_minor", type: BIGINT, notNull: true, default: "0" },
      { name: "reserved_minor", type: BIGINT, notNull: true, default: "0" },
    ],
    unique: [["scope_kind", "scope_key", "period_kind", "period_key"]],
    uniqueIndexes: [{ name: "budget_limits_scope_uniq", columns: ["scope_kind", "scope_key", "period_kind", "period_key"] }],
    indexes: [["idx_budget_period", ["period_kind", "period_key"]]],
  },
  {
    name: "call_reservations",
    identity: "id",
    columns: [
      { name: "id", type: IDENTITY_ID, primaryKey: true },
      { name: "request_id", type: TEXT, notNull: true },
      { name: "attempt_id", type: TEXT, notNull: true },
      { name: "config_id", type: BIGINT },
      { name: "price_version", type: TEXT },
      { name: "ceiling_minor", type: BIGINT, notNull: true },
      { name: "job_state", type: TEXT, notNull: true },
      { name: "provider_request_id", type: TEXT },
      { name: "created_at", type: TEXT, notNull: true },
      { name: "settled_at", type: TEXT },
    ],
    unique: [["request_id", "attempt_id"]],
    uniqueIndexes: [{ name: "call_reservations_request_uniq", columns: ["request_id", "attempt_id"] }],
    indexes: [["idx_reservation_state", ["job_state", "id"]]],
  },
  {
    name: "provider_usage_logs",
    identity: "id",
    columns: [
      { name: "id", type: IDENTITY_ID, primaryKey: true },
      { name: "created_at", type: TEXT, notNull: true },
      { name: "category", type: TEXT, notNull: true },
      { name: "provider_code", type: TEXT },
      { name: "reservation_id", type: BIGINT },
      { name: "event_kind", type: TEXT, notNull: true },
      { name: "amount_minor", type: BIGINT },
      { name: "job_state", type: TEXT },
      { name: "note", type: TEXT },
    ],
    unique: [],
    uniqueIndexes: [],
    indexes: [["idx_usage_created", ["created_at", "id"]]],
  },
];

function columnDef(column) {
  const parts = [quoteIdent(column.name), column.type];
  if (column.primaryKey) parts.push("PRIMARY KEY");
  if (column.notNull) parts.push("NOT NULL");
  if (column.default != null) parts.push(`DEFAULT ${column.default}`);
  return parts.join(" ");
}

function createTableStatement(table) {
  const lines = table.columns.map((column) => `  ${columnDef(column)}`);
  for (const columns of table.unique) {
    lines.push(`  UNIQUE (${columns.map(quoteIdent).join(", ")})`);
  }
  return `CREATE TABLE IF NOT EXISTS ${quoteIdent(table.name)} (\n${lines.join(",\n")}\n)`;
}

export function budgetPgCreateTableStatements() {
  return BUDGET_PG_TABLES.map(createTableStatement);
}

// ADD COLUMN IF NOT EXISTS：既有表（legacy 鏡射出來的）之後若缺欄，冪等補上。
// id／主鍵欄不在此列（由 CREATE TABLE 負責；ADD COLUMN 不能安全補 identity PK）。
export function budgetPgAddColumnStatements() {
  const statements = [];
  for (const table of BUDGET_PG_TABLES) {
    for (const column of table.columns) {
      if (column.primaryKey) continue;
      const def = [
        column.type,
        column.notNull ? "NOT NULL" : "",
        column.default != null ? `DEFAULT ${column.default}` : "",
      ].filter(Boolean).join(" ");
      statements.push(`ALTER TABLE ${quoteIdent(table.name)} ADD COLUMN IF NOT EXISTS ${quoteIdent(column.name)} ${def}`);
    }
  }
  return statements;
}

export function budgetPgIndexStatements() {
  return BUDGET_PG_TABLES.flatMap((table) =>
    table.indexes.map(([name, columns]) =>
      `CREATE INDEX IF NOT EXISTS ${quoteIdent(name)} ON ${quoteIdent(table.name)} (${columns.map(quoteIdent).join(", ")})`,
    ),
  );
}

export function budgetPgUniqueIndexStatements() {
  return BUDGET_PG_TABLES.flatMap((table) =>
    table.uniqueIndexes.map(({ name, columns }) =>
      `CREATE UNIQUE INDEX IF NOT EXISTS ${quoteIdent(name)} ON ${quoteIdent(table.name)} (${columns.map(quoteIdent).join(", ")})`,
    ),
  );
}

// 建表＋補欄＋索引（含唯一索引）＝PG 側權威 schema 的完整冪等 DDL。
export function budgetPgDdlStatements() {
  return [
    ...budgetPgCreateTableStatements(),
    ...budgetPgAddColumnStatements(),
    ...budgetPgIndexStatements(),
    ...budgetPgUniqueIndexStatements(),
  ];
}

// 序號對齊（冪等、可重跑）：只對有 identity id 的表發 setval 到 max(id)+1。
// setval(seq, v, false) 令下一次 nextval 回傳 v（＝第一筆空位 id），重跑結果不變。
export function budgetPgIdentityResyncStatements() {
  return BUDGET_PG_TABLES.filter((table) => table.identity).map((table) => {
    const tableName = quoteIdent(table.name);
    const column = quoteIdent(table.identity);
    return `SELECT setval(pg_get_serial_sequence('${tableName}', '${column}'), (SELECT COALESCE(MAX(${column}), 0) + 1 FROM ${tableName}), false)`;
  });
}

// 對應 repo.BUDGET_TABLES 的順序（供呼叫端診斷／報告用）。
export const BUDGET_PG_TABLE_NAMES = BUDGET_PG_TABLES.map((table) => table.name);
