// 內容文件（條款／隱私權／各類規則）的 driver-aware 入口（PG 島嶼，2026-09-27）。
//
// 涵蓋的路由：
//   GET    /api/public/documents           列出必要文件（註冊條款、隱私權）
//   GET    /api/public/documents/:type     取目前生效的那一版
//   GET    /api/admin/documents            後台列表（含草稿）
//   GET    /api/admin/documents/:id        單筆 ＋ 稽核事件
//   GET    /api/admin/documents/:id/events 稽核事件
//   POST   /api/admin/documents            建立草稿
//   PATCH  /api/admin/documents/:id        更新草稿（已發布者只能改旗標）
//   POST   /api/admin/documents/:id/publish
//   POST   /api/admin/documents/:id/new-version
//   另外 `legalCopyFromDocuments()` 是多條路由（`/api/disclaimer`、`/api/me`、註冊流程…）
//   的共用卡點，一併移植。
//
// 🚨 **這一輪的方言難點：不可變性是用 SQLite TRIGGER 實作的。**
//
// `ensureContentDocumentSchema()`（contentDocuments.js:106）建了一個
// `content_documents_immutable` 触发器：`OLD.status = 'published'` 时，只要
// body／title／format／check_label／content_hash／version／document_type 有變就
// `RAISE(ABORT, 'published_document_immutable')`。
//
// **PG 完全不吃這個語法**（沒有 `IS NOT OLD.x`、沒有 `RAISE(ABORT)`）。要等價的話得寫
// plpgsql 函式 ＋ `CREATE TRIGGER ... EXECUTE FUNCTION`，而且 `IS NOT OLD.x` 要換成
// `IS DISTINCT FROM`。**這不是「有就好」的加固：它是一條真正的業務規則**
// （已發布的條款不能事後被改掉——那會讓使用者同意過的版本與畫面不一致），
// 少了它就等於 PG 上沒有這個保護。
//
// ⚠️ 第二個坑：`nextVersion()` 用 `MAX(version)`，PG 回的是 bigint 字串，要 `Number()`。
import { resolveDbDriver } from "./dbDriver.js";
import { sqliteHandle } from "./db.js";
import { sharedPgDriver } from "./pgSharedDriver.js";
import { toPostgresSql } from "./sqlDialect.js";
import { sqliteFallbackAllowed } from "./sqliteFallback.js";
import {
  INSERT_EVENT_SQL,
  NEXT_VERSION_SQL,
  assertType,
  auditEventParams,
  createDraft as createDraftSync,
  createDraftFromPublished as createDraftFromPublishedSync,
  documentFingerprint,
  getDocumentById as getDocumentByIdSync,
  getEffectiveDocument as getEffectiveDocumentSync,
  getRequiredRegistrationDocuments as getRequiredRegistrationDocumentsSync,
  httpError,
  inEffect,
  iso,
  listDocumentEvents as listDocumentEventsSync,
  legalCopyFromDocuments as legalCopyFromDocumentsSync,
  listDocuments as listDocumentsSync,
  publishDocument as publishDocumentSync,
  rowToDoc,
  updateDraft as updateDraftSync,
  validatePayload,
} from "./contentDocuments.js";
import { defaultLegalCopy } from "./legalCopy.js";

const REGISTRATION_DOC_TYPES = ["registration_terms", "privacy_notice"];

// ---- 語句文字（逐字對應 contentDocuments.js 的行號）----
export const LIST_BY_TYPE_SQL =
  "SELECT * FROM content_documents WHERE document_type=? ORDER BY version DESC, id DESC"; // contentDocuments.js:209
export const LIST_ALL_SQL =
  "SELECT * FROM content_documents ORDER BY document_type, version DESC, id DESC"; // contentDocuments.js:210
export const DOC_BY_ID_SQL = "SELECT * FROM content_documents WHERE id=?"; // contentDocuments.js:215
export const DOC_BY_TYPE_VERSION_SQL =
  "SELECT * FROM content_documents WHERE document_type=? AND version=?"; // contentDocuments.js:220
export const PUBLISHED_BY_TYPE_SQL =
  "SELECT * FROM content_documents WHERE document_type=? AND status='published' ORDER BY version DESC, id DESC"; // contentDocuments.js:229
export const INSERT_DRAFT_SQL =
  `INSERT INTO content_documents(
     document_type, version, title, body, format, check_label, status, enabled,
     requires_reacceptance, effective_from, effective_until, content_hash, created_by, created_at, supersedes_id
   ) VALUES (?,?,?,?,?,?, 'draft', ?, ?, ?, ?, ?, ?, ?, ?) RETURNING *`; // contentDocuments.js:271（PG 用 RETURNING）
export const UPDATE_DRAFT_SQL =
  `UPDATE content_documents SET title=?, body=?, format=?, check_label=?, enabled=?, requires_reacceptance=?,
   effective_from=?, effective_until=?, content_hash=? WHERE id=? AND status='draft'`; // contentDocuments.js:314
export const UPDATE_PUBLISHED_FLAGS_SQL =
  `UPDATE content_documents SET enabled=?, requires_reacceptance=?, effective_from=?, effective_until=?
   WHERE id=? AND status='published'`; // contentDocuments.js:334
export const PUBLISH_SQL =
  "UPDATE content_documents SET status='published', published_at=?, enabled=1 WHERE id=?"; // contentDocuments.js:353
export const EVENTS_BY_DOC_SQL =
  "SELECT * FROM content_document_events WHERE document_id=? ORDER BY id DESC LIMIT ?"; // contentDocuments.js:379
export const EVENTS_BY_TYPE_SQL =
  "SELECT * FROM content_document_events WHERE document_type=? ORDER BY id DESC LIMIT ?"; // contentDocuments.js:382
export const EVENTS_ALL_SQL = "SELECT * FROM content_document_events ORDER BY id DESC LIMIT ?"; // contentDocuments.js:384
export const COUNT_BY_TYPE_SQL = "SELECT COUNT(*) n FROM content_documents WHERE document_type=?"; // contentDocuments.js:426

// ---- schema ----
export const PG_SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS content_documents (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     document_type TEXT NOT NULL,
     version BIGINT NOT NULL,
     title TEXT NOT NULL,
     body TEXT NOT NULL,
     format TEXT NOT NULL DEFAULT 'plain',
     check_label TEXT NOT NULL DEFAULT '',
     status TEXT NOT NULL DEFAULT 'draft',
     enabled BIGINT NOT NULL DEFAULT 1,
     requires_reacceptance BIGINT NOT NULL DEFAULT 0,
     effective_from TEXT,
     effective_until TEXT,
     content_hash TEXT NOT NULL,
     created_by BIGINT,
     created_at TEXT NOT NULL,
     published_at TEXT,
     supersedes_id BIGINT
   )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_content_documents_type_version
     ON content_documents(document_type, version)`,
  `CREATE INDEX IF NOT EXISTS idx_content_documents_effective
     ON content_documents(document_type, status, enabled, version)`,
  `CREATE TABLE IF NOT EXISTS content_document_events (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     document_id BIGINT,
     document_type TEXT NOT NULL,
     version BIGINT,
     action TEXT NOT NULL,
     actor_id BIGINT,
     content_hash TEXT,
     created_at TEXT NOT NULL
   )`,
  `CREATE INDEX IF NOT EXISTS idx_content_document_events_doc
     ON content_document_events(document_type, document_id, created_at)`,
];

// PG 版的不可變性守衛。對應 contentDocuments.js:106 的 SQLite TRIGGER：
//   * `NEW.x IS NOT OLD.x` → `NEW.x IS DISTINCT FROM OLD.x`（PG 的 IS NOT 不能比 NULL）
//   * `RAISE(ABORT, …)` → `RAISE EXCEPTION '…'`（plpgsql）
//   * `CREATE TRIGGER IF NOT EXISTS` PG 沒有 ⇒ 先 DROP 再 CREATE（idempotent）
export const PG_IMMUTABLE_FUNCTION_SQL = `CREATE OR REPLACE FUNCTION content_documents_immutable_fn()
   RETURNS trigger AS $$
   BEGIN
     IF OLD.status = 'published' AND (
       NEW.body IS DISTINCT FROM OLD.body
       OR NEW.title IS DISTINCT FROM OLD.title
       OR NEW.format IS DISTINCT FROM OLD.format
       OR NEW.check_label IS DISTINCT FROM OLD.check_label
       OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
       OR NEW.version IS DISTINCT FROM OLD.version
       OR NEW.document_type IS DISTINCT FROM OLD.document_type
     ) THEN
       RAISE EXCEPTION 'published_document_immutable';
     END IF;
     RETURN NEW;
   END;
   $$ LANGUAGE plpgsql`;
export const PG_DROP_TRIGGER_SQL = "DROP TRIGGER IF EXISTS content_documents_immutable ON content_documents";
export const PG_CREATE_TRIGGER_SQL =
  `CREATE TRIGGER content_documents_immutable BEFORE UPDATE ON content_documents
   FOR EACH ROW EXECUTE FUNCTION content_documents_immutable_fn()`;

const isPg = (options = {}) => (options.driver || resolveDbDriver()) === "postgres";
const firstRow = (rows) => (Array.isArray(rows) && rows.length ? rows[0] : null);
// PG 的 MAX()／COUNT() 是 bigint，node-pg 回字串。
const countOf = (rows) => Number(firstRow(rows)?.n) || 0;

async function pgExec(options = {}) {
  if (options.exec) return options.exec;
  const pgDriver = options.pgDriver || (await sharedPgDriver());
  return (sql, params = []) => pgDriver.query(toPostgresSql(sql), params).then((res) => res.rows);
}

// 每個 pgDriver 只建一次 schema。沿用 budgetGuardAsync／listingToolsAsync／memberMediaAsync 的形狀。
const schemaReady = new WeakMap();
export async function ensureContentDocumentStoreOnce(pgDriver) {
  if (!pgDriver) return;
  if (schemaReady.has(pgDriver)) return schemaReady.get(pgDriver);
  const ready = (async () => {
    for (const sql of PG_SCHEMA_STATEMENTS) await pgDriver.exec(sql);
    await pgDriver.exec(PG_IMMUTABLE_FUNCTION_SQL);
    await pgDriver.exec(PG_DROP_TRIGGER_SQL);
    await pgDriver.exec(PG_CREATE_TRIGGER_SQL);
  })();
  schemaReady.set(pgDriver, ready);
  try {
    await ready;
  } catch (error) {
    schemaReady.delete(pgDriver); // 失敗不要快取，下次再試
    throw error;
  }
}

async function pgHandle(options = {}) {
  const exec = await pgExec(options);
  if (!options.exec) await ensureContentDocumentStoreOnce(options.pgDriver || (await sharedPgDriver()));
  return exec;
}

async function withFallback(options, runPostgres, runSqlite) {
  if (!isPg(options)) return runSqlite();
  try {
    return await runPostgres(await pgHandle(options));
  } catch (error) {
    if (!sqliteFallbackAllowed(options)) throw error;
    return runSqlite();
  }
}

async function withFallbackTx(options, runPostgres, runSqlite) {
  if (!isPg(options)) return runSqlite();
  try {
    if (options.exec) return await runPostgres(options.exec);
    const pgDriver = options.pgDriver || (await sharedPgDriver());
    await ensureContentDocumentStoreOnce(pgDriver);
    return await pgDriver.withTransaction(async (client) => {
      const exec = (sql, params = []) => client.query(toPostgresSql(sql), params).then((res) => res.rows);
      return runPostgres(exec);
    });
  } catch (error) {
    if (!sqliteFallbackAllowed(options, { write: true })) throw error;
    return runSqlite();
  }
}

// 稽核事件：同步版是 `audit()`。參數組法共用 `auditEventParams()`（含 `iso(now)`），
// 所以只有 SQL 那一句是新的。
async function writeAudit(exec, entry) {
  await exec(INSERT_EVENT_SQL, auditEventParams(entry));
}

const readById = async (exec, id) => rowToDoc(firstRow(await exec(DOC_BY_ID_SQL, [Number(id) || 0])));
const readByTypeVersion = async (exec, type, version) =>
  rowToDoc(firstRow(await exec(DOC_BY_TYPE_VERSION_SQL, [assertType(type), Number(version) || 0])));

async function nextVersionAsync(exec, type) {
  return countOf(await exec(NEXT_VERSION_SQL, [type])) + 1;
}

// ---- 讀取 ----

export async function listDocumentsAsync({ type, includeDrafts = false } = {}, options = {}) {
  return withFallback(
    options,
    async (exec) => {
      const rows = type
        ? await exec(LIST_BY_TYPE_SQL, [assertType(type)])
        : await exec(LIST_ALL_SQL);
      return rows.map(rowToDoc).filter((doc) => includeDrafts || doc.status === "published");
    },
    () => listDocumentsSync(sqliteHandle(), { type, includeDrafts }),
  );
}

export async function getDocumentByIdAsync(id, options = {}) {
  return withFallback(
    options,
    (exec) => readById(exec, id),
    () => getDocumentByIdSync(sqliteHandle(), id),
  );
}

export async function getEffectiveDocumentAsync(type, { now = new Date(), ...options } = {}) {
  return withFallback(
    options,
    async (exec) => {
      const id = assertType(type);
      const nowIso = iso(now);
      const rows = (await exec(PUBLISHED_BY_TYPE_SQL, [id])).map(rowToDoc);
      return rows.find((doc) => inEffect(doc, nowIso)) || null;
    },
    () => getEffectiveDocumentSync(sqliteHandle(), type, { now }),
  );
}

export async function getRequiredRegistrationDocumentsAsync({ now = new Date(), ...options } = {}) {
  if (!isPg(options)) return getRequiredRegistrationDocumentsSync(sqliteHandle(), { now });
  const out = [];
  for (const type of REGISTRATION_DOC_TYPES) {
    const doc = await getEffectiveDocumentAsync(type, { now, ...options });
    if (doc) out.push(doc);
  }
  return out;
}

export async function listDocumentEventsAsync({ type, documentId, limit = 50 } = {}, options = {}) {
  const n = Math.min(200, Math.max(1, Number(limit) || 50));
  return withFallback(
    options,
    async (exec) => {
      if (documentId) return exec(EVENTS_BY_DOC_SQL, [Number(documentId), n]);
      if (type) return exec(EVENTS_BY_TYPE_SQL, [assertType(type), n]);
      return exec(EVENTS_ALL_SQL, [n]);
    },
    () => listDocumentEventsSync(sqliteHandle(), { type, documentId, limit }),
  );
}

// 多條路由的共用卡點（`/api/disclaimer`、`/api/me`、註冊流程…）。
export async function legalCopyFromDocumentsAsync({ now = new Date(), ...options } = {}) {
  if (!isPg(options)) return legalCopyFromDocumentsSync(sqliteHandle(), { now });
  const terms = await getEffectiveDocumentAsync("registration_terms", { now, ...options });
  const privacy = await getEffectiveDocumentAsync("privacy_notice", { now, ...options });
  const defaults = defaultLegalCopy();
  return {
    version: terms ? `v${terms.version}` : defaults.version,
    disclaimer: terms?.body || defaults.disclaimer,
    disclaimerCheck: terms?.check_label || defaults.disclaimerCheck,
    privacy: privacy?.body || defaults.privacy,
    privacyCheck: privacy?.check_label || defaults.privacyCheck,
    text: terms?.body || defaults.disclaimer,
    privacy_text: privacy?.body || defaults.privacy,
  };
}

// ---- 寫入 ----

export async function createDraftAsync(input = {}, { actorId = 0, now = new Date(), ...options } = {}) {
  if (!isPg(options)) return createDraftSync(sqliteHandle(), input, { actorId, now });
  const type = assertType(input.document_type);
  const fields = validatePayload(input); // 純驗證，兩邊共用同一份
  return withFallbackTx(options, async (exec) => {
    const version = Number(input.version) > 0 ? Number(input.version) : await nextVersionAsync(exec, type);
    if (await readByTypeVersion(exec, type, version)) throw httpError("這個版本號已存在", 409);
    const fingerprint = documentFingerprint({ document_type: type, version, ...fields });
    const row = firstRow(await exec(INSERT_DRAFT_SQL, [
      type, version, fields.title, fields.body, fields.format, fields.check_label,
      input.enabled === false ? 0 : 1,
      input.requires_reacceptance === true ? 1 : 0,
      input.effective_from || null,
      input.effective_until || null,
      fingerprint,
      Number(actorId) || null,
      iso(now),
      Number(input.supersedes_id) || null,
    ]));
    const doc = rowToDoc(row);
    await writeAudit(exec, {
      document_id: doc.id, document_type: type, version, action: "draft_create",
      actor_id: actorId, content_hash: fingerprint, now,
    });
    return doc;
  }, () => createDraftSync(sqliteHandle(), input, { actorId, now }));
}

export async function updateDraftAsync(id, input = {}, { actorId = 0, now = new Date(), ...options } = {}) {
  if (!isPg(options)) return updateDraftSync(sqliteHandle(), id, input, { actorId, now });
  return withFallbackTx(options, async (exec) => {
    const doc = await readById(exec, id);
    if (!doc) throw httpError("找不到文件", 404);
    if (doc.status === "published") {
      // 已發布版本**只能改旗標**，本文欄位一律拒絕（與同步版同義）。
      if (input.title != null || input.body != null || input.format != null || input.check_label != null) {
        throw httpError("已發布版本不可改本文；請建立新版本", 409);
      }
      await updatePublishedFlagsAsync(exec, doc, input, { actorId, now });
      return readById(exec, doc.id);
    }
    const fields = validatePayload({
      title: input.title ?? doc.title,
      body: input.body ?? doc.body,
      format: input.format ?? doc.format,
      check_label: input.check_label ?? doc.check_label,
    });
    const hash = documentFingerprint({ document_type: doc.document_type, version: doc.version, ...fields });
    await exec(UPDATE_DRAFT_SQL, [
      fields.title, fields.body, fields.format, fields.check_label,
      flagValue(input.enabled, doc.enabled),
      flagValue(input.requires_reacceptance, doc.requires_reacceptance),
      input.effective_from === undefined ? doc.effective_from : (input.effective_from || null),
      input.effective_until === undefined ? doc.effective_until : (input.effective_until || null),
      hash,
      doc.id,
    ]);
    await writeAudit(exec, {
      document_id: doc.id, document_type: doc.document_type, version: doc.version,
      action: "draft_update", actor_id: actorId, content_hash: hash, now,
    });
    return readById(exec, doc.id);
  }, () => updateDraftSync(sqliteHandle(), id, input, { actorId, now }));
}

// 同步版的 `input.x === false ? 0 : (input.x === true ? 1 : doc.x)`——三態：
// 沒帶就沿用舊值。抽出來讓兩處（草稿／已發布旗標）與同步版語意一致。
function flagValue(input, current) {
  if (input === false) return 0;
  if (input === true) return 1;
  return current ? 1 : 0;
}

async function updatePublishedFlagsAsync(exec, doc, input, { actorId, now }) {
  await exec(UPDATE_PUBLISHED_FLAGS_SQL, [
    flagValue(input.enabled, doc.enabled),
    flagValue(input.requires_reacceptance, doc.requires_reacceptance),
    input.effective_from === undefined ? doc.effective_from : (input.effective_from || null),
    input.effective_until === undefined ? doc.effective_until : (input.effective_until || null),
    doc.id,
  ]);
  await writeAudit(exec, {
    document_id: doc.id, document_type: doc.document_type, version: doc.version,
    action: "flags_update", actor_id: actorId, content_hash: doc.content_hash, now,
  });
}

export async function publishDocumentAsync(id, { actorId = 0, now = new Date(), ...options } = {}) {
  if (!isPg(options)) return publishDocumentSync(sqliteHandle(), id, { actorId, now });
  return withFallbackTx(options, async (exec) => {
    const doc = await readById(exec, id);
    if (!doc) throw httpError("找不到文件", 404);
    if (doc.status === "published") return doc; // 已發布 ⇒ 直接回，不重複寫稽核（同步版同義）
    await exec(PUBLISH_SQL, [iso(now), doc.id]);
    const published = await readById(exec, doc.id);
    await writeAudit(exec, {
      document_id: published.id, document_type: published.document_type, version: published.version,
      action: "publish", actor_id: actorId, content_hash: published.content_hash, now,
    });
    return published;
  }, () => publishDocumentSync(sqliteHandle(), id, { actorId, now }));
}

export async function createDraftFromPublishedAsync(id, { actorId = 0, now = new Date(), ...options } = {}) {
  if (!isPg(options)) return createDraftFromPublishedSync(sqliteHandle(), id, { actorId, now });
  const doc = await getDocumentByIdAsync(id, options);
  if (!doc) throw httpError("找不到文件", 404);
  if (doc.status !== "published") throw httpError("只能從已發布版本開新草稿", 400);
  return createDraftAsync({
    document_type: doc.document_type,
    title: doc.title,
    body: doc.body,
    format: doc.format,
    check_label: doc.check_label,
    enabled: true,
    requires_reacceptance: false,
    supersedes_id: doc.id,
  }, { actorId, now, ...options });
}

// 供測試與其他模組檢查「PG 上有沒有那條不可變規則」。
export async function publishedDocumentIsImmutable(pgDriverOrExec) {
  const exec = typeof pgDriverOrExec === "function"
    ? pgDriverOrExec
    : (sql, params = []) => pgDriverOrExec.query(toPostgresSql(sql), params).then((r) => r.rows);
  const row = firstRow(await exec(
    "SELECT 1 AS ok FROM pg_trigger WHERE tgname='content_documents_immutable' AND NOT tgisinternal",
  ));
  return Boolean(row);
}
