// data_revision 變更紀錄的 PostgreSQL 原生 schema（sqlite-exit 批次 C）。
//
// 為什麼需要：persistListing（寫入端）在寫 PG 之前會用節點 SQLite handle 把 data_revision
// 鏡射到 PG（ensureChangeLogStoreOnce → ensureDataRevisionTable(db) → ensurePgSchema →
// resyncIdentitySequences）。正式 PG 模式把 PG_NO_SQLITE_OPEN=1 打開後沒有 SQLite handle，
// 所以把權威 schema 定義搬到 PG 側（與 budgetPgSchema.js 同一慣例）。
//
// 欄位型別逐欄對齊正式庫 5151_shadow（information_schema.columns / pg_indexes 唯讀實測，
// 2026-10-09）：
//   id          BIGINT GENERATED BY DEFAULT AS IDENTITY（PK，序列 public.data_revision_id_seq）
//   entity_type TEXT NOT NULL
//   entity_id   BIGINT（可空）
//   event_type  TEXT NOT NULL
//   created_at  BIGINT NOT NULL
//   idx_data_revision_id：非唯一索引（SQLite 側 dataRevision.js 的 DDL 同源）。
//
// 這裡刻意補上「SQLite 鏡射」在沒有 handle 時做不到、但 PG 一定要有的事：
//   1. CREATE TABLE IF NOT EXISTS 用 PG 原生型別（BIGINT identity）建表；
//   2. 帶 id 的匯入不會推進 identity 序號 → 初始化時 setval 到 max(id)+1（冪等、可重跑）。
import { quoteIdent } from "./pgSchema.js";

const TABLE = {
  name: "data_revision",
  identity: "id",
  columns: [
    { name: "id", type: "BIGINT GENERATED BY DEFAULT AS IDENTITY", primaryKey: true },
    { name: "entity_type", type: "TEXT", notNull: true },
    { name: "entity_id", type: "BIGINT" },
    { name: "event_type", type: "TEXT", notNull: true },
    { name: "created_at", type: "BIGINT", notNull: true },
  ],
  indexes: [["idx_data_revision_id", ["id"]]],
};

function columnDef(column) {
  const parts = [quoteIdent(column.name), column.type];
  if (column.primaryKey) parts.push("PRIMARY KEY");
  if (column.notNull) parts.push("NOT NULL");
  return parts.join(" ");
}

function createTableStatement(table) {
  const lines = table.columns.map((column) => `  ${columnDef(column)}`);
  return `CREATE TABLE IF NOT EXISTS ${quoteIdent(table.name)} (\n${lines.join(",\n")}\n)`;
}

export function dataRevisionPgCreateTableStatements() {
  return [createTableStatement(TABLE)];
}

export function dataRevisionPgIndexStatements() {
  return TABLE.indexes.map(([name, columns]) =>
    `CREATE INDEX IF NOT EXISTS ${quoteIdent(name)} ON ${quoteIdent(TABLE.name)} (${columns.map(quoteIdent).join(", ")})`,
  );
}

// 建表＋索引＝PG 側權威 schema 的完整冪等 DDL。
export function dataRevisionPgDdlStatements() {
  return [...dataRevisionPgCreateTableStatements(), ...dataRevisionPgIndexStatements()];
}

// 序號對齊（冪等、可重跑）：setval(seq, max(id)+1, false) 令下一次 nextval 回傳第一筆空位 id。
export function dataRevisionPgIdentityResyncStatements() {
  const tableName = quoteIdent(TABLE.name);
  const column = quoteIdent(TABLE.identity);
  return [
    `SELECT setval(pg_get_serial_sequence('${tableName}', '${column}'), (SELECT COALESCE(MAX(${column}), 0) + 1 FROM ${tableName}), false)`,
  ];
}
