// demand_posts／demand_replies／demand_reports 的 PostgreSQL 原生 schema（開閘 D-0021 批次）。
//
// 為什麼需要它：`demandAsync.ensureDemandStoreOnce()` 原本靠 `ensurePgSchema(pgDriver, sqliteHandle(),
// { tables: DEMAND_TABLES })` 鏡射建表——schema 的權威是 SQLite（PRAGMA table_info / sqlite_master）。
// PG_NO_SQLITE_OPEN=1 後根本沒有 SQLite handle，開閘時那三張表（早就被 cutover 鏡射建好）卻
// 因為 `ensurePgSchema` 對「已存在的表」仍會先讀 SQLite schema 而整條拋錯（/api/demand、
// /api/wish-rooms、/api/demand/:id、/api/wish-rooms/:id、/api/public/wish-room/:id 全 400）。
//
// 這裡把權威 schema 定義搬到 PG 側（資料驅動，同 budgetPgSchema.js 的寫法）：
//   1. 欄位型別／可空性／預設值逐欄對齊正式庫 5151_shadow（information_schema.columns 唯讀實測），
//      也與 SQLite 側 `demand.js ensureDemandSchema` 同源：INTEGER→BIGINT、REAL→DOUBLE PRECISION、
//      INTEGER PRIMARY KEY AUTOINCREMENT→BIGINT GENERATED BY DEFAULT AS IDENTITY。
//   2. 部分唯一索引（「同一人只能有一則 open」的 idx_demand_one_open 等）在 SQLite 是隱式、
//      `ensurePgSchema` 鏡射時能帶過去（sqlite_master 有 sql），但原生路徑沒有 sqlite 可讀，
//      所以這裡顯式宣告（WHERE 子句兩邊都合法）。
import { quoteIdent } from "./pgSchema.js";

const TEXT = "TEXT";
const BIGINT = "BIGINT";
const DOUBLE = "DOUBLE PRECISION";
const IDENTITY_ID = `${BIGINT} GENERATED BY DEFAULT AS IDENTITY`;

export const DEMAND_PG_TABLES = [
  {
    name: "demand_posts",
    identity: "id",
    columns: [
      { name: "id", type: IDENTITY_ID, primaryKey: true },
      { name: "user_id", type: BIGINT, notNull: true },
      { name: "districts", type: TEXT, notNull: true, default: "'[]'" },
      { name: "rent_max", type: BIGINT, notNull: true, default: "0" },
      { name: "housing_type", type: TEXT, notNull: true, default: "'any'" },
      { name: "mrt_walk", type: BIGINT, notNull: true, default: "0" },
      { name: "body", type: TEXT, notNull: true, default: "''" },
      { name: "status", type: TEXT, notNull: true, default: "'open'" },
      { name: "created_at", type: TEXT, notNull: true },
      { name: "expires_at", type: TEXT, notNull: true },
      { name: "closed_at", type: TEXT },
      { name: "city", type: TEXT, notNull: true, default: "''" },
      { name: "location_note", type: TEXT, notNull: true, default: "''" },
      { name: "rent_min", type: BIGINT, notNull: true, default: "0" },
      { name: "includes_management", type: BIGINT, notNull: true, default: "0" },
      { name: "ping_min", type: DOUBLE, notNull: true, default: "0" },
      { name: "layout", type: TEXT, notNull: true, default: "''" },
      { name: "move_in_date", type: TEXT, notNull: true, default: "''" },
      { name: "lease_duration", type: TEXT, notNull: true, default: "''" },
      { name: "transit_note", type: TEXT, notNull: true, default: "''" },
      { name: "destination_note", type: TEXT, notNull: true, default: "''" },
      { name: "commute_minutes", type: BIGINT, notNull: true, default: "0" },
      { name: "must_have", type: TEXT, notNull: true, default: "'[]'" },
      { name: "nice_to_have", type: TEXT, notNull: true, default: "'[]'" },
      { name: "avoid", type: TEXT, notNull: true, default: "'[]'" },
      { name: "contact_name", type: TEXT, notNull: true, default: "''" },
      { name: "phone", type: TEXT, notNull: true, default: "''" },
      { name: "line_url", type: TEXT, notNull: true, default: "''" },
      { name: "updated_at", type: TEXT },
      { name: "published_at", type: TEXT },
      { name: "public_token", type: TEXT },
      { name: "lifecycle", type: TEXT },
      { name: "last_confirmed_at", type: TEXT },
      { name: "last_active_at", type: TEXT },
      { name: "activity_score", type: DOUBLE },
      { name: "continuous_active_from", type: TEXT },
      { name: "condition_choices", type: TEXT },
      { name: "fee_includes", type: TEXT, notNull: true, default: "''" },
      { name: "fee_includes_at", type: TEXT },
      { name: "closed_reason", type: TEXT },
      { name: "lifecycle_migrated_at", type: TEXT },
      { name: "fixture_namespace", type: TEXT },
      { name: "legacy_numeric_share", type: BIGINT, notNull: true, default: "0" },
    ],
  },
  {
    name: "demand_replies",
    identity: "id",
    columns: [
      { name: "id", type: IDENTITY_ID, primaryKey: true },
      { name: "post_id", type: BIGINT, notNull: true },
      { name: "user_id", type: BIGINT, notNull: true },
      { name: "body", type: TEXT, notNull: true },
      { name: "created_at", type: TEXT, notNull: true },
      { name: "hidden", type: BIGINT, notNull: true, default: "0" },
    ],
  },
  {
    name: "demand_reports",
    identity: "id",
    columns: [
      { name: "id", type: IDENTITY_ID, primaryKey: true },
      { name: "target_type", type: TEXT, notNull: true },
      { name: "target_id", type: BIGINT, notNull: true },
      { name: "user_id", type: BIGINT, notNull: true },
      { name: "reason", type: TEXT, notNull: true, default: "''" },
      { name: "created_at", type: TEXT, notNull: true },
    ],
  },
];

function columnDef(column) {
  const parts = [quoteIdent(column.name), column.type];
  if (column.primaryKey) parts.push("PRIMARY KEY");
  if (column.notNull) parts.push("NOT NULL");
  if (column.default != null) parts.push(`DEFAULT ${column.default}`);
  return parts.join(" ");
}

function createTableStatement(table) {
  const lines = table.columns.map((column) => `  ${columnDef(column)}`);
  return `CREATE TABLE IF NOT EXISTS ${quoteIdent(table.name)} (\n${lines.join(",\n")}\n)`;
}

export function demandPgCreateTableStatements() {
  return DEMAND_PG_TABLES.map(createTableStatement);
}

// 既有表（cutover 鏡射出來的）之後若缺欄，冪等補上（id／主鍵除外）。與同步版
// demand.js `addWishColumns()` 對應同一份欄位清單。
export function demandPgAddColumnStatements() {
  const statements = [];
  for (const table of DEMAND_PG_TABLES) {
    for (const column of table.columns) {
      if (column.primaryKey) continue;
      const def = [
        column.type,
        column.notNull ? "NOT NULL" : "",
        column.default != null ? `DEFAULT ${column.default}` : "",
      ].filter(Boolean).join(" ");
      statements.push(`ALTER TABLE ${quoteIdent(table.name)} ADD COLUMN IF NOT EXISTS ${quoteIdent(column.name)} ${def}`);
    }
  }
  return statements;
}

// 索引／唯一索引（含部分索引的 WHERE 子句）。語句逐字對齊 demand.js `ensureDemandSchema`。
// ⚠️ 部分唯一索引是「同一人只能有一則 open／draft／mutable」與「public_token 唯一」的實作，
// 正式庫（5151_shadow）上這三張表原本只有 pkey，所以要靠這裡（與原生 ALTER）補齊。
export function demandPgIndexStatements() {
  return [
    "CREATE INDEX IF NOT EXISTS idx_demand_posts_status ON demand_posts(status, expires_at)",
    "CREATE INDEX IF NOT EXISTS idx_demand_replies_post ON demand_replies(post_id, created_at)",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_demand_one_open ON demand_posts(user_id) WHERE status = 'open'",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_demand_one_draft ON demand_posts(user_id) WHERE status = 'draft'",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_demand_one_mutable ON demand_posts(user_id) WHERE status IN ('open', 'draft')",
    "CREATE INDEX IF NOT EXISTS idx_demand_posts_updated ON demand_posts(status, updated_at, id)",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_demand_public_token ON demand_posts(public_token) WHERE public_token IS NOT NULL AND public_token != ''",
    "CREATE INDEX IF NOT EXISTS idx_demand_match_open ON demand_posts(status, lifecycle, rent_max, id) WHERE status = 'open'",
    "CREATE INDEX IF NOT EXISTS idx_demand_match_lifecycle ON demand_posts(lifecycle, status, id)",
    "CREATE INDEX IF NOT EXISTS idx_demand_match_eligible ON demand_posts(rent_max, id) WHERE status = 'open' AND COALESCE(NULLIF(lifecycle, ''), 'active') IN ('active', 'needs_confirmation')",
  ];
}

export function demandPgDdlStatements() {
  return [
    ...demandPgCreateTableStatements(),
    ...demandPgAddColumnStatements(),
    ...demandPgIndexStatements(),
  ];
}

export const DEMAND_PG_TABLE_NAMES = DEMAND_PG_TABLES.map((table) => table.name);
