// 意見回饋附圖（C3）的 driver-aware 入口（PG 島嶼）。
//
// 同步版的邏輯全部在 `feedbackMedia.js`；這裡只負責：
//   1. 走 PG 時把 SQL 翻成 PG 方言，並補建 schema（PG 的 `ADD COLUMN IF NOT EXISTS`）
//   2. 依 `sqliteFallbackAllowed()` 決定失敗時要不要回退本機 handle
//
// 附件**只寫本機檔案**（`DATA_DIR/feedback-media/`），所以檔案 I/O 兩個 driver 共用，
// 沒有 R2 物件要清（與 memberMedia 不同：那條路上傳時會推 CDN）。
//
// PG 的 demand/feedback 島嶼有 `withTransaction`（見 feedbackAsync.js）；附件 claim 會在
// 那個交易內執行，所以這裡另外提供吃 `exec` 的 `claimFeedbackAttachmentsAsync()`。

import path from "node:path";
import { randomBytes } from "node:crypto";
import { unlinkSync, writeFileSync } from "node:fs";
import { resolveDbDriver } from "./dbDriver.js";
import { sqliteHandle } from "./db.js";
import { sharedPgDriver } from "./pgSharedDriver.js";
import { toPostgresSql } from "./sqlDialect.js";
import { sqliteFallbackAllowed } from "./sqliteFallback.js";
import {
  FEEDBACK_ATTACHMENT_MAX,
  claimFeedbackAttachments as claimFeedbackAttachmentsSync,
  countOpenFeedbackAttachments as countOpenFeedbackAttachmentsSync,
  deleteFeedbackAttachment as deleteFeedbackAttachmentSync,
  feedbackMediaDir,
  getFeedbackAttachment as getFeedbackAttachmentSync,
  getOpenFeedbackAttachment as getOpenFeedbackAttachmentSync,
  listFeedbackAttachments as listFeedbackAttachmentsSync,
  listFeedbackAttachmentsFor as listFeedbackAttachmentsForSync,
  listOpenFeedbackAttachments as listOpenFeedbackAttachmentsSync,
  publicAttachmentShape,
  removeFeedbackAttachmentFiles,
  saveFeedbackAttachment as saveFeedbackAttachmentSync,
  streamFeedbackAttachment,
  sweepOrphanFeedbackAttachments as sweepOrphanFeedbackAttachmentsSync,
  validateFeedbackImage,
} from "./feedbackMedia.js";

const isPg = (options = {}) => (options.driver || resolveDbDriver()) === "postgres";
const rowsOf = (raw) => (Array.isArray(raw) ? raw : (raw?.rows || []));
const firstRow = (rows) => (Array.isArray(rows) && rows.length ? rows[0] : null);

export const PG_SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS feedback_attachment (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     feedback_id BIGINT NOT NULL DEFAULT 0,
     user_id BIGINT NOT NULL,
     storage_key TEXT NOT NULL,
     thumb_key TEXT,
     mime TEXT NOT NULL,
     format TEXT NOT NULL,
     width BIGINT,
     height BIGINT,
     bytes BIGINT,
     digest TEXT,
     created_at TEXT NOT NULL,
     claimed_at TEXT,
     deleted_at TEXT
   )`,
  "CREATE INDEX IF NOT EXISTS idx_feedback_attachment_feedback ON feedback_attachment(feedback_id)",
  "CREATE INDEX IF NOT EXISTS idx_feedback_attachment_user ON feedback_attachment(user_id, created_at)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_feedback_attachment_key ON feedback_attachment(storage_key)",
];
// `ensurePgSchema()` 對既有表只送 `CREATE TABLE IF NOT EXISTS`（等於 no-op），補不了欄位；
// PG 專屬的 ALTER 要在這裡送（SQLite 沒有 `ADD COLUMN IF NOT EXISTS`）。
export const PG_ALTER_STATEMENTS = [
  "ALTER TABLE feedback_attachment ADD COLUMN IF NOT EXISTS claimed_at TEXT",
  "ALTER TABLE feedback_attachment ADD COLUMN IF NOT EXISTS deleted_at TEXT",
];

const schemaReady = new WeakMap();
export async function ensureFeedbackMediaStoreOnce(pgDriver) {
  if (!pgDriver) return;
  if (schemaReady.has(pgDriver)) return schemaReady.get(pgDriver);
  const ready = (async () => {
    for (const sql of PG_SCHEMA_STATEMENTS) await pgDriver.exec(sql);
    for (const sql of PG_ALTER_STATEMENTS) await pgDriver.exec(sql);
  })();
  schemaReady.set(pgDriver, ready);
  try {
    await ready;
  } catch (error) {
    schemaReady.delete(pgDriver); // 失敗不要快取，下次再試
    throw error;
  }
}

async function pgExec(options = {}) {
  if (options.exec) {
    const injected = options.exec;
    return async (sql, params = []) => rowsOf(await injected(sql, params));
  }
  const pgDriver = options.pgDriver || (await sharedPgDriver());
  await ensureFeedbackMediaStoreOnce(pgDriver);
  return (sql, params = []) => pgDriver.query(toPostgresSql(sql), params).then((res) => res.rows);
}

async function withFallback(options, { write = false }, runPostgres, runSqlite) {
  if (!isPg(options)) return runSqlite();
  try {
    return await runPostgres(await pgExec(options));
  } catch (error) {
    if (!sqliteFallbackAllowed(options, { write })) throw error;
    return runSqlite();
  }
}

function httpError(message, status = 400, code = "") {
  const e = new Error(message);
  e.status = status;
  if (code) e.code = code;
  return e;
}

export async function countOpenFeedbackAttachmentsAsync(userId, options = {}) {
  return withFallback(options, {}, async (exec) => {
    const rows = await exec(
      "SELECT COUNT(*) AS n FROM feedback_attachment WHERE user_id=? AND feedback_id=0 AND deleted_at IS NULL",
      [Number(userId)],
    );
    return Number(firstRow(rows)?.n) || 0;
  }, () => countOpenFeedbackAttachmentsSync(sqliteHandle(), userId));
}

/**
 * 上傳。**刻意 fail-closed**：PG 寫入失敗不靜默回退本機（否則正式站會出現
 * 「PG 沒有、本機有」的孤兒檔），與 `saveMemberMediaAsync` 同一個政策。
 */
export async function saveFeedbackAttachmentAsync(userId, buffer, options = {}) {
  if (!isPg(options)) return saveFeedbackAttachmentSync(sqliteHandle(), userId, buffer, options);
  const exec = await pgExec(options);
  const uid = Number(userId) || 0;
  if (!uid) throw httpError("請先登入才能上傳圖片", 401, "login_required");
  const used = Number(firstRow(await exec(
    "SELECT COUNT(*) AS n FROM feedback_attachment WHERE user_id=? AND feedback_id=0 AND deleted_at IS NULL",
    [uid],
  ))?.n) || 0;
  if (used >= FEEDBACK_ATTACHMENT_MAX) {
    throw httpError(`每則回饋最多 ${FEEDBACK_ATTACHMENT_MAX} 張圖片，請先刪除再上傳`, 409, "attachment_limit");
  }
  // 驗證（含真的解碼）與寫檔兩個 driver 共用；只有 SQL 由這裡以 PG 方言送出。
  const processed = await validateFeedbackImage(buffer, options);
  const key = randomBytes(16).toString("hex");
  const mainName = `${key}.jpg`;
  const thumbName = `${key}_t.jpg`;
  const dir = feedbackMediaDir();
  const ts = (options.now instanceof Date ? options.now : new Date(options.now || Date.now())).toISOString();
  const written = [];
  try {
    writeFileSync(path.join(dir, mainName), processed.main.buffer);
    written.push(mainName);
    writeFileSync(path.join(dir, thumbName), processed.thumb.buffer);
    written.push(thumbName);
    const rows = await exec(
      `INSERT INTO feedback_attachment(user_id, storage_key, thumb_key, mime, format, width, height, bytes, digest, created_at)
       VALUES (?,?,?,?,?,?,?,?,?,?) RETURNING id`,
      [uid, mainName, thumbName, processed.mime, processed.format,
        processed.main.width, processed.main.height, processed.main.buffer.length, processed.digest, ts],
    );
    const id = Number(firstRow(rows)?.id) || 0;
    return publicAttachmentShape({
      id,
      bytes: processed.main.buffer.length,
      width: processed.main.width,
      height: processed.main.height,
      mime: processed.mime,
    });
  } catch (err) {
    for (const name of written) {
      try { unlinkSync(path.join(dir, name)); } catch { /* 清不掉就交給 sweep */ }
    }
    throw err;
  }
}

export async function deleteFeedbackAttachmentAsync(userId, id, options = {}) {
  return withFallback(options, { write: true }, async (exec) => {
    const rows = await exec(
      "SELECT * FROM feedback_attachment WHERE id=? AND user_id=? AND feedback_id=0 AND deleted_at IS NULL",
      [Number(id), Number(userId)],
    );
    const row = firstRow(rows);
    if (!row) throw httpError("找不到這張圖片，或已經送出回饋", 404, "attachment_not_found");
    const ts = (options.now instanceof Date ? options.now : new Date(options.now || Date.now())).toISOString();
    await exec("UPDATE feedback_attachment SET deleted_at=? WHERE id=?", [ts, Number(row.id)]);
    removeFeedbackAttachmentFiles(row);
    return { ok: true, id: Number(row.id) };
  }, () => deleteFeedbackAttachmentSync(sqliteHandle(), userId, id, options));
}

/** 一次抓多則回饋的附件（後台列表用；避免 N+1）。回傳 Map<feedbackId, rows>。 */
export async function listFeedbackAttachmentsForAsync(feedbackIds, options = {}) {
  const ids = [...new Set((Array.isArray(feedbackIds) ? feedbackIds : [])
    .map((id) => Number(id)).filter((id) => Number.isInteger(id) && id > 0))];
  if (!ids.length) return new Map();
  return withFallback(options, {}, async (exec) => {
    const marks = ids.map(() => "?").join(",");
    const rows = await exec(
      `SELECT * FROM feedback_attachment WHERE feedback_id IN (${marks}) AND deleted_at IS NULL ORDER BY id ASC`,
      ids,
    );
    const out = new Map();
    for (const row of rows) {
      const key = Number(row.feedback_id);
      if (!out.has(key)) out.set(key, []);
      out.get(key).push(publicAttachmentShape(row));
    }
    return out;
  }, () => listFeedbackAttachmentsForSync(sqliteHandle(), ids));
}

/** 我目前還沒送出的附件（同步／PG 共用同一個形狀）。 */
export async function listOpenFeedbackAttachmentsAsync(userId, options = {}) {
  return withFallback(options, {}, async (exec) => {
    const rows = await exec(
      "SELECT * FROM feedback_attachment WHERE user_id=? AND feedback_id=0 AND deleted_at IS NULL ORDER BY id ASC",
      [Number(userId)],
    );
    return rows.map((row) => publicAttachmentShape(row, { scope: "admin" }));
  }, () => listOpenFeedbackAttachmentsSync(sqliteHandle(), userId));
}

/** 同步版 getOpenFeedbackAttachment() 的 driver-aware 版本（R3 的會員預覽）。 */
export async function getOpenFeedbackAttachmentAsync(userId, id, options = {}) {
  return withFallback(options, {}, async (exec) => {
    const rows = await exec(
      "SELECT * FROM feedback_attachment WHERE id=? AND user_id=? AND feedback_id=0 AND deleted_at IS NULL",
      [Number(id), Number(userId)],
    );
    return firstRow(rows) || null;
  }, () => getOpenFeedbackAttachmentSync(sqliteHandle(), userId, id));
}

export async function getFeedbackAttachmentAsync(id, options = {}) {
  return withFallback(options, {}, async (exec) => {
    const rows = await exec("SELECT * FROM feedback_attachment WHERE id=? AND deleted_at IS NULL", [Number(id)]);
    return firstRow(rows) || null;
  }, () => getFeedbackAttachmentSync(sqliteHandle(), id));
}

export async function listFeedbackAttachmentsAsync(feedbackId, options = {}) {
  return withFallback(options, {}, async (exec) => {
    const rows = await exec(
      "SELECT * FROM feedback_attachment WHERE feedback_id=? AND deleted_at IS NULL ORDER BY id ASC",
      [Number(feedbackId)],
    );
    return rows.map((row) => publicAttachmentShape(row, { scope: "admin" }));
  }, () => listFeedbackAttachmentsSync(sqliteHandle(), feedbackId));
}

/** 在 `submitFeedbackAsync()` 的同一個 PG 交易內呼叫（`exec` 由呼叫端提供）。 */
export async function claimFeedbackAttachmentsAsync(exec, userId, ids, feedbackId, now = new Date()) {
  const list = [...new Set((Array.isArray(ids) ? ids : []).map((id) => Number(id)).filter((id) => Number.isInteger(id) && id > 0))];
  if (!list.length) return 0;
  const marks = list.map(() => "?").join(",");
  const ts = (now instanceof Date ? now : new Date(now)).toISOString();
  // 呼叫端傳進來的 exec 有兩種形狀（裸陣列 / `{rows,rowCount}`，feedbackAsync 的 tx 是後者），
  // 這裡一律用 `rowsOf()` 收斂，避免「明明改了卻比對到 undefined 長度」而誤丟 409。
  const rows = rowsOf(await exec(
    `UPDATE feedback_attachment SET feedback_id=?, claimed_at=?
     WHERE id IN (${marks}) AND user_id=? AND feedback_id=0 AND deleted_at IS NULL RETURNING id`,
    // 參數順序同同步版：feedback_id、claimed_at、id IN (…)、user_id。
    [Number(feedbackId), ts, ...list, Number(userId)],
  ));
  if (rows.length !== list.length) throw httpError("附件已失效，請重新上傳", 409, "attachment_stale");
  return list.length;
}

/** 同步版 claim（給 SQLite 路徑與測試用；語意與 PG 版逐字相同）。 */
export { claimFeedbackAttachmentsSync };

export async function sweepOrphanFeedbackAttachmentsAsync(options = {}) {
  return withFallback(options, { write: true }, async (exec) => {
    const ts = (options.now instanceof Date ? options.now : new Date(options.now || Date.now())).getTime();
    const olderThanMs = Number(options.olderThanMs) || 24 * 60 * 60 * 1000;
    const cutoff = new Date(ts - Math.max(0, olderThanMs)).toISOString();
    const rows = await exec(
      "SELECT * FROM feedback_attachment WHERE feedback_id=0 AND deleted_at IS NULL AND created_at < ?",
      [cutoff],
    );
    let removed = 0;
    for (const row of rows) {
      try {
        await exec("UPDATE feedback_attachment SET deleted_at=? WHERE id=?", [new Date(ts).toISOString(), Number(row.id)]);
        removeFeedbackAttachmentFiles(row);
        removed += 1;
      } catch { /* 單列失敗不影響其他列 */ }
    }
    return { scanned: rows.length, removed };
  }, () => sweepOrphanFeedbackAttachmentsSync(sqliteHandle(), options));
}

export { streamFeedbackAttachment };
