// Driver-aware listing enrich reads/admin stats（2.3b 第一段）＋ 佇列寫入路徑（2.3b 第二段）。
//
// sqlite   - 原 listingEnrichQueue.js 函式（行為不變）。
// postgres - repository/listingEnrich.js 的同一份語句文字。
// 查詢結果的組裝（summarizeEnrichMetrics 的統計）**逐字沿用** listingEnrichQueue.js 的 stageSummary()。
//
// 第二段的關鍵差別：claim／reclaim 要判斷「有沒有搶到、回收幾筆」，
// SQLite 是 res.changes、PostgreSQL 是 rowCount，所以寫入路徑用 withFallbackCounted()
// （exec 的形狀是 { rows, rowCount }；離線替身也要照這個形狀回，只回陣列會被當成 rowCount 0）。
import {
  CLAIM_LEASE_MS,
  claimEnrichJobs as claimEnrichJobsSync,
  claimTakePlan,
  clickRefreshResult,
  CLICK_PRIORITY,
  enrichEnqueueEligible,
  enqueueEnrichPlan,
  enqueueListingEnrich as enqueueListingEnrichSync,
  enqueuePriority,
  enrichMetricPlan,
  finishEnrichJobSync,
  finishEnrichPlan,
  getListingPrep as getListingPrepSync,
  jobRunOwns,
  jobStillOwnsRun as jobStillOwnsRunSync,
  listingPrepAdminStats as listingPrepAdminStatsSync,
  prepCheckedUpdateSync,
  reclaimStaleEnrichJobs as reclaimStaleEnrichJobsSync,
  recordEnrichMetric as recordEnrichMetricSync,
  ensureListingPrepSchema as ensureListingPrepSchemaSync,
  requestClickPlan,
  requestClickRefresh as requestClickRefreshSync,
  seedHousepriceEnrichJobs as seedHousepriceEnrichJobsSync,
  seedRowMissing,
  stageSummary,
  summarizeEnrichMetrics as summarizeEnrichMetricsSync,
  WATCH_PRIORITY,
} from "./listingEnrichQueue.js";
import { ensurePgSchema, resyncIdentitySequences } from "./pgSchema.js";
import { resolveDbDriver } from "./dbDriver.js";
import { sharedPgDriver } from "./pgSharedDriver.js";
import { toPostgresSql } from "./sqlDialect.js";
import * as repo from "./repository/listingEnrich.js";

async function withFallback(options, runPostgres, runSqlite) {
  const driver = options.driver || resolveDbDriver();
  if (driver !== "postgres") return runSqlite();
  try {
    if (options.exec) return await runPostgres(options.exec);
    const pgDriver = options.pgDriver || (await sharedPgDriver());
    const exec = (sql, params = []) => pgDriver.query(toPostgresSql(sql), params).then((res) => res.rows);
    return await runPostgres(exec);
  } catch (error) {
    if (options.strict) throw error;
    return runSqlite();
  }
}

// ---- 2.3b 第二段：寫入路徑的共用工具 -----------------------------------------

function firstRow(raw) {
  const rows = Array.isArray(raw) ? raw : (raw && raw.rows) || [];
  return rows[0] || null;
}

// PG 的 query() 回 { rows, rowCount }；node:sqlite 的 run() 回 { changes }。
// 兩種形狀都正規化成 { rows, rowCount }，寫入路徑才判斷得出「有沒有生效」。
function normalizeResult(raw) {
  if (Array.isArray(raw)) return { rows: raw, rowCount: Number(raw.rowCount ?? raw.length) || 0 };
  const rows = (raw && raw.rows) || [];
  const changes = Number(raw && raw.changes);
  return { rows, rowCount: Number((raw && raw.rowCount) ?? (Number.isFinite(changes) ? changes : rows.length)) || 0 };
}

// 每次呼叫都帶著 sqliteHandle：PG 分支才有 SQLite schema 可以鏡射建表。
function withConn(options, conn) {
  if (!conn || options.sqliteHandle) return options;
  return { ...options, sqliteHandle: conn };
}

// PG 端這三張表的準備：鏡射建表 → 重新對齊 identity 序號 → 補欄位。
// 序號那一步不能省：影子站是「帶 id 匯入」的，PostgreSQL 不會因為帶 id 的 INSERT 推進
// GENERATED BY DEFAULT AS IDENTITY 序號，第一次不帶 id 的寫入就會撞 pkey
// （2026-09-23 實測：listing_enrich_jobs 有 9145 列，序號還停在 1）。
export async function preparePgEnrichStore(pgDriver, sqliteDb) {
  await ensurePgSchema(pgDriver, sqliteDb, { tables: repo.LISTING_ENRICH_TABLES });
  await resyncIdentitySequences(pgDriver, sqliteDb, { tables: repo.LISTING_ENRICH_TABLES });
}

// 欄位探測：PostgreSQL 沒有 PRAGMA table_info()，改查 information_schema.columns；
// 缺的欄位才 ALTER TABLE（與 SQLite 端 ensureColumn 的目的一樣）。TEXT／INTEGER 語法兩邊相通。
export async function syncListingEnrichColumns(exec, runDdl) {
  const added = [];
  for (const mig of repo.LISTING_ENRICH_COLUMN_MIGRATIONS) {
    const probe = repo.columnProbeQuery(mig.table);
    const { rows } = await exec(probe.sql, probe.params);
    if (!(rows || []).some((row) => String(row.column_name) === mig.name)) {
      await runDdl(repo.addColumnQuery(mig.table, mig.name, mig.ddl).sql);
      added.push(`${mig.table}.${mig.name}`);
    }
  }
  return added;
}

// schema（表 ＋ 欄位）只準備一次：DDL 是 idempotent，但每個 entry point 都跑一次太浪費。
// 有真 driver 時以它為 key；只有注入 exec（測試／探針）時才用 exec 當 key。
const schemaReady = new WeakSet();

async function ensureEnrichSchemaOnce(exec, pgDriver, sqliteDb) {
  const key = pgDriver || exec;
  if (schemaReady.has(key)) return;
  if (pgDriver && sqliteDb) await preparePgEnrichStore(pgDriver, sqliteDb);
  await syncListingEnrichColumns(exec, (sql) => exec(sql, []));
  schemaReady.add(key);
}

// 寫入路徑的 withFallback：差別在 exec 回傳 { rows, rowCount }（回退語意與第一段相同），
// 另外會在第一次呼叫時把 PG schema 準備好（PG 端不走 schemaMigrations，所以由這裡負責）。
async function withFallbackCounted(options, runPostgres, runSqlite) {
  const driver = options.driver || resolveDbDriver();
  if (driver !== "postgres") return runSqlite();
  try {
    if (options.exec) {
      const injected = (sql, params = []) => Promise.resolve(options.exec(sql, params)).then(normalizeResult);
      await ensureEnrichSchemaOnce(injected, null, options.sqliteHandle);
      return await runPostgres(injected);
    }
    const pgDriver = options.pgDriver || (await sharedPgDriver());
    const exec = async (sql, params = []) => normalizeResult(await pgDriver.query(toPostgresSql(sql), params));
    await ensureEnrichSchemaOnce(exec, pgDriver, options.sqliteHandle);
    return await runPostgres(exec);
  } catch (error) {
    if (options.strict) throw error;
    return runSqlite();
  }
}

// listingEnrichQueue.js getListingPrep()
export function getListingPrepAsync(conn, postId, options = {}) {
  const opts = { ...options, sqliteHandle: conn };
  return withFallback(opts, (exec) => repo.readPrepRow(exec, postId), () => getListingPrepSync(conn, postId));
}

// listingEnrichQueue.js summarizeEnrichMetrics()：查詢走 driver，統計用同一支 stageSummary。
export function summarizeEnrichMetricsAsync(conn, options = {}) {
  const opts = { ...options, sqliteHandle: conn };
  const stages = ["queued_ms", "start_ms", "fetch_ms", "parse_ms", "locate_ms", "route_ms", "ready_ms", "first_ready_ms", "attempt_wait_ms"];
  const shape = (rows) => {
    const out = { samples: rows.length, stages: {}, byOutcome: {} };
    for (const key of stages) out.stages[key] = stageSummary(rows, key);
    for (const outcome of ["succeeded", "failed", "waiting"]) {
      const subset = rows.filter((row) => String(row.outcome || "") === outcome);
      out.byOutcome[outcome] = { samples: subset.length, stages: {} };
      for (const key of stages) out.byOutcome[outcome].stages[key] = stageSummary(subset, key);
    }
    return out;
  };
  return withFallback(opts, async (exec) => shape(await repo.readMetricsRows(exec)), () => summarizeEnrichMetricsSync(conn));
}

// listingEnrichQueue.js listingPrepAdminStats()
export function listingPrepAdminStatsAsync(conn, options = {}) {
  const opts = { ...options, sqliteHandle: conn };
  return withFallback(
    opts,
    async (exec) => {
      const one = async (q) => ((await exec(q.sql, q.params)) || [])[0] || {};
      const pending = await one(repo.prepPendingCountQuery());
      const ready = await one(repo.prepReadyCountQuery());
      const jobs = await one(repo.enrichJobsSummaryQuery());
      const rawErrors = ((await exec(repo.enrichErrorBreakdownQuery().sql, repo.enrichErrorBreakdownQuery().params)) || []);
      const errors = rawErrors.map((row) => ({ reason: row.reason, n: Number(row.n) || 0 }));
      const metrics = await summarizeEnrichMetricsAsync(conn, { ...opts, exec });
      return {
        pendingPrep: Number(pending.n) || 0,
        readyPrep: Number(ready.n) || 0,
        waitingJobs: Number(jobs.waiting) || 0,
        runningJobs: Number(jobs.running) || 0,
        oldestWaitAt: jobs.oldest || "",
        lastSuccessAt: jobs.last_success || "",
        errors,
        metrics,
      };
    },
    () => listingPrepAdminStatsSync(conn),
  );
}

export function listingEnrichAsyncContext() {
  return repo;
}

// ---- 2.3b 第二段：寫入路徑的 async 入口 --------------------------------------
//
// 簽名一律是 (conn, ...args, options)：conn 是 SQLite handle，也是 PG 分支鏡射 schema 的來源；
// options 支援 { driver, pgDriver, exec, strict, sqliteHandle }（與第一段相同）。

// listingEnrichQueue.js ensureListingPrepSchema()：PG 模式不能跑 PRAGMA，改用
// information_schema.columns 探測（syncListingEnrichColumns），補上缺的欄位。
export function ensureListingPrepSchemaAsync(conn, options = {}) {
  const opts = withConn(options, conn);
  return withFallbackCounted(
    opts,
    async (exec) => {
      if (!opts.exec) {
        const pgDriver = opts.pgDriver || (await sharedPgDriver());
        await preparePgEnrichStore(pgDriver, opts.sqliteHandle || conn);
      }
      const added = await syncListingEnrichColumns(exec, (sql) => exec(sql, []));
      return { driver: "postgres", tables: repo.LISTING_ENRICH_TABLES, added };
    },
    () => ensureListingPrepSchemaSync(conn),
  );
}

// 單筆入列（PG 路徑）。seed 也走這一支，避免「入列」的判斷出現兩份。
async function enqueueViaExec(exec, listing, { via = "scheduler", priority, missing = [], now = Date.now() } = {}) {
  if (!enrichEnqueueEligible(listing)) return null;
  const postId = Number(listing.post_id);
  const prio = enqueuePriority(via, priority);
  const jobQuery = repo.enrichJobByPostIdQuery(postId);
  const existing = firstRow(await exec(jobQuery.sql, jobQuery.params));
  const plan = enqueueEnrichPlan(existing, { postId, prio, via, missing, now });
  await exec(plan.sql, plan.params);
  return firstRow(await exec(jobQuery.sql, jobQuery.params));
}

// listingEnrichQueue.js enqueueListingEnrich()
export function enqueueListingEnrichAsync(conn, listing, {
  via = "scheduler",
  priority,
  missing = [],
  now = Date.now(),
} = {}, options = {}) {
  const opts = withConn(options, conn);
  return withFallbackCounted(
    opts,
    (exec) => enqueueViaExec(exec, listing, { via, priority, missing, now }),
    () => enqueueListingEnrichSync(conn, listing, { via, priority, missing, now }),
  );
}

// listingEnrichQueue.js seedHousepriceEnrichJobs()：候選查詢改讀 PG（原本讀本機 SQLite，
// PG 模式下會拿到空的或以本機資料產出錯誤的工作），每一列再走 enqueueViaExec。
export function seedHousepriceEnrichJobsAsync(conn, { limit = 80, isEnabled = () => true } = {}, options = {}) {
  const opts = withConn(options, conn);
  if (!isEnabled("houseprice")) return 0;
  return withFallbackCounted(
    opts,
    async (exec) => {
      const q = repo.seedEnrichCandidatesQuery(limit);
      const rows = (await exec(q.sql, q.params)).rows || [];
      let n = 0;
      for (const row of rows) {
        await enqueueViaExec(exec, row, { via: "scheduler", missing: seedRowMissing(row) });
        n += 1;
      }
      return n;
    },
    () => seedHousepriceEnrichJobsSync(conn, { limit, isEnabled }),
  );
}

// listingEnrichQueue.js reclaimStaleEnrichJobs()：回傳回收筆數（PG 用 rowCount）。
export function reclaimStaleEnrichJobsAsync(conn, now = Date.now(), options = {}) {
  const opts = withConn(options, conn);
  const q = repo.reclaimStaleEnrichJobsQuery(new Date(now).toISOString());
  return withFallbackCounted(
    opts,
    async (exec) => {
      const { rowCount } = await exec(q.sql, q.params);
      return Number(rowCount) || 0;
    },
    () => reclaimStaleEnrichJobsSync(conn, now),
  );
}

// 單列搶單（PG：與 sync 的 claimOne 同一順序、同一份 SQL；名額分配共用 claimTakePlan）。
async function claimOneViaExec(exec, opts = {}, now = Date.now()) {
  const stamp = new Date(now).toISOString();
  const leaseUntil = new Date(now + CLAIM_LEASE_MS).toISOString();
  const candidates = repo.claimCandidatesQuery({ ...opts, stamp });
  const row = firstRow(await exec(candidates.sql, candidates.params));
  if (!row) return null;
  const lease = repo.leaseEnrichJobQuery({ stamp, leaseUntil, id: row.id });
  const { rowCount } = await exec(lease.sql, lease.params);
  if (!Number(rowCount)) return null;
  const byId = repo.enrichJobByIdQuery(row.id);
  return firstRow(await exec(byId.sql, byId.params));
}

async function claimEnrichJobsViaExec(exec, { limit = 6 } = {}, now = Date.now()) {
  const reclaim = repo.reclaimStaleEnrichJobsQuery(new Date(now).toISOString());
  await exec(reclaim.sql, reclaim.params);
  const cap = Math.max(1, Math.min(Number(limit) || 6, 12));
  const claimed = [];
  const seen = new Set();
  const take = async (opts, n) => {
    for (let i = 0; i < n; i += 1) {
      const row = await claimOneViaExec(exec, opts, now);
      if (!row || seen.has(row.id)) break;
      seen.add(row.id);
      claimed.push(row);
    }
  };
  for (const step of claimTakePlan(cap)) {
    await take(step.opts, step.slots < 0 ? cap - claimed.length : step.slots);
  }
  return claimed;
}

// listingEnrichQueue.js claimEnrichJobs()
export function claimEnrichJobsAsync(conn, { limit = 6 } = {}, options = {}) {
  const opts = withConn(options, conn);
  return withFallbackCounted(
    opts,
    (exec) => claimEnrichJobsViaExec(exec, { limit }),
    () => claimEnrichJobsSync(conn, { limit }),
  );
}

// listingEnrichQueue.js finishJob()：回 { stale, superseded, status }（與 sync 版同義）。
export function finishEnrichJobAsync(conn, job, patch = {}, options = {}) {
  const opts = withConn(options, conn);
  return withFallbackCounted(
    opts,
    async (exec) => {
      const runSeq = repo.enrichJobRunSeqQuery(job.id);
      const latest = firstRow(await exec(runSeq.sql, runSeq.params));
      const plan = finishEnrichPlan(job, patch, latest);
      if (plan.stale) return { stale: true };
      await exec(plan.sql, plan.params);
      return { stale: false, superseded: plan.superseded, status: plan.status };
    },
    () => finishEnrichJobSync(conn, job, patch),
  );
}

// listingEnrichQueue.js recordEnrichMetric()（sync 版不回傳值，這裡也保持一致）
export function recordEnrichMetricAsync(conn, job, timings = {}, options = {}) {
  const opts = withConn(options, conn);
  const plan = enrichMetricPlan(job, timings);
  return withFallbackCounted(
    opts,
    async (exec) => {
      await exec(plan.sql, plan.params);
    },
    () => recordEnrichMetricSync(conn, job, timings),
  );
}

// listingEnrichQueue.js jobStillOwnsRun()：PG 上讀同一張表的最新 run_seq／request_seq。
export function jobStillOwnsRunAsync(conn, job, options = {}) {
  const opts = withConn(options, conn);
  return withFallback(
    opts,
    async (exec) => {
      if (!job?.id) return false;
      const q = repo.enrichJobRunSeqQuery(job.id);
      return jobRunOwns(((await exec(q.sql, q.params)) || [])[0] || null, job);
    },
    () => jobStillOwnsRunSync(conn, job),
  );
}

// listingEnrichQueue.js 的 inline prep UPDATE（PROBE_INCONCLUSIVE 分支）
export function prepCheckedUpdateAsync(conn, { postId, reason, now = Date.now() } = {}, options = {}) {
  const opts = withConn(options, conn);
  const q = repo.prepCheckedUpdateQuery({ stamp: new Date(now).toISOString(), reason, postId });
  return withFallbackCounted(
    opts,
    async (exec) => {
      await exec(q.sql, q.params);
    },
    () => prepCheckedUpdateSync(conn, { postId, reason, now }),
  );
}

// listingEnrichQueue.js requestClickRefresh()
export function requestClickRefreshAsync(conn, listing, via = "click", options = {}) {
  const opts = withConn(options, conn);
  return withFallbackCounted(
    opts,
    async (exec) => {
      if (!enrichEnqueueEligible(listing)) return { queued: false };
      const jobQuery = repo.enrichJobByPostIdQuery(listing.post_id);
      const prep = await repo.readPrepRow(exec, listing.post_id);
      const existing = firstRow(await exec(jobQuery.sql, jobQuery.params));
      const decision = requestClickPlan(prep, existing, listing, via);
      let job = existing;
      if (decision.enqueue) {
        await exec(decision.enqueue.sql, decision.enqueue.params);
        job = firstRow(await exec(jobQuery.sql, jobQuery.params));
      }
      return clickRefreshResult(decision, job);
    },
    () => requestClickRefreshSync(conn, listing, via),
  );
}

// listingEnrichQueue.js processListingEnrichBatch() 用的 bundle（helpers.enrichQueue）。
// 方法簽名刻意與同步函式一致（第一個參數都是 conn），所以 SQLite 模式就等於直接呼叫它們。
export function listingEnrichQueueFacade(conn, options = {}) {
  const opts = withConn(options, conn);
  const driver = opts.driver || resolveDbDriver();
  const useConn = (c) => c || conn;
  return {
    driver,
    seed: (c, seedOpts) => seedHousepriceEnrichJobsAsync(useConn(c), seedOpts, opts),
    claim: (c, args) => claimEnrichJobsAsync(useConn(c), args, opts),
    finish: (c, job, patch) => finishEnrichJobAsync(useConn(c), job, patch, opts),
    metric: (c, job, timings) => recordEnrichMetricAsync(useConn(c), job, timings, opts),
    ownsRun: (c, job) => jobStillOwnsRunAsync(useConn(c), job, opts),
    getPrep: (c, postId) => getListingPrepAsync(useConn(c), postId, opts),
    prepChecked: (c, args) => prepCheckedUpdateAsync(useConn(c), args, opts),
  };
}

