// Keep the complete candidate shape in one place. A literal object retains
// V8 fast properties; pg array mode avoids inserting wide-row keys one at a time.
export function candidateRowFromValues(values) {
  return {
    post_id: values[0],
    source: values[1],
    source_id: values[2],
    source_key: values[3],
    url: values[4],
    price: values[5],
    price_num: values[6],
    extra_fee: values[7],
    extra_fees: values[8],
    extra_fee_text: values[9],
    price_contain_text: values[10],
    title: values[11],
    address: values[12],
    address_norm: values[13],
    area_name: values[14],
    layout: values[15],
    floor_name: values[16],
    kind_name: values[17],
    tags: values[18],
    role_name: values[19],
    contact_name: values[20],
    contact_role: values[21],
    contact_uid: values[22],
    agency: values[23],
    lat: values[24],
    lng: values[25],
    geo_source: values[26],
    location_class: values[27],
    match_post_id: values[28],
    match_level: values[29],
    match_verdict: values[30],
    match_rejected: values[31],
    offline: values[32],
    offline_confirmed: values[33],
    hidden: values[34],
    hidden_at: values[35],
    last_event: values[36],
    first_seen_at: values[37],
    last_seen_at: values[38],
    refresh_time: values[39],
    listed_by_user_id: values[40],
    self_status: values[41],
  };
}

export const LIST_CANDIDATE_KEYS = Object.freeze(Object.keys(candidateRowFromValues([])));
export const LIST_CANDIDATE_COLUMNS = LIST_CANDIDATE_KEYS.join(", ");

// Only for the canonical 42-column PG candidate projection, before decoration.
// Explicit fields avoid enumerating/copying a wide object for every personal view.
// Generic rows keep using overlayPersonal's spread so additional fields survive.
export function candidateRowWithPersonal(row, personal) {
  return {
    post_id: row.post_id,
    source: row.source,
    source_id: row.source_id,
    source_key: row.source_key,
    url: row.url,
    price: row.price,
    price_num: row.price_num,
    extra_fee: row.extra_fee,
    extra_fees: row.extra_fees,
    extra_fee_text: row.extra_fee_text,
    price_contain_text: row.price_contain_text,
    title: row.title,
    address: row.address,
    address_norm: row.address_norm,
    area_name: row.area_name,
    layout: row.layout,
    floor_name: row.floor_name,
    kind_name: row.kind_name,
    tags: row.tags,
    role_name: row.role_name,
    contact_name: row.contact_name,
    contact_role: row.contact_role,
    contact_uid: row.contact_uid,
    agency: row.agency,
    lat: row.lat,
    lng: row.lng,
    geo_source: row.geo_source,
    location_class: row.location_class,
    match_post_id: row.match_post_id,
    match_level: row.match_level,
    match_verdict: row.match_verdict,
    match_rejected: row.match_rejected,
    offline: row.offline,
    offline_confirmed: row.offline_confirmed,
    hidden: personal.hidden,
    hidden_at: personal.hidden_at,
    last_event: row.last_event,
    first_seen_at: row.first_seen_at,
    last_seen_at: row.last_seen_at,
    refresh_time: row.refresh_time,
    listed_by_user_id: row.listed_by_user_id,
    self_status: row.self_status,
    viewed: personal.viewed,
    watched: personal.watched,
    watch_note: personal.watch_note,
    viewed_at: personal.viewed_at,
    watched_at: personal.watched_at,
  };
}
