/** 來源欄位矩陣：實際可取得／已解析／尚未解析。不得把「未提供」寫成已觀測 null。 */

export const FIELD_STATUS = Object.freeze({
  PARSED: "parsed",
  MISSING: "missing",
  NOT_PROVIDED: "not_provided",
  NOT_FETCHED: "not_fetched",
  PARSE_FAILED: "parse_failed",
});

export const SOURCE_FIELD_MATRIX = [
  {
    source: "591",
    label: "591 租屋",
    fields: {
      address: "parsed",
      community: "parsed",
      floor: "parsed",
      rent: "parsed",
      extra_fees: "parsed",
      area: "parsed",
      layout: "parsed",
      kind: "parsed",
      age: "not_fetched",
      elevator: "parsed",
      parking: "not_fetched",
      photos: "cover_only",
      posted_at: "not_provided",
      source_updated_at: "parsed",
      fetched_at: "parsed",
      url: "parsed",
      source_id: "parsed",
      latlng: "parsed",
      contact: "parsed",
    },
  },
  {
    source: "hbhousing",
    label: "住商不動產",
    fields: {
      address: "parsed",
      community: "missing",
      floor: "parsed",
      rent: "parsed",
      extra_fees: "partial",
      area: "parsed",
      layout: "parsed",
      kind: "parsed",
      photos: "cover_only",
      source_updated_at: "missing",
      fetched_at: "parsed",
      url: "parsed",
      source_id: "parsed",
      latlng: "parsed",
      contact: "not_provided",
    },
  },
  {
    source: "sinyi",
    label: "信義房屋",
    fields: {
      address: "parsed",
      community: "parsed",
      floor: "parsed",
      rent: "parsed",
      extra_fees: "partial",
      area: "parsed",
      layout: "parsed",
      kind: "parsed",
      photos: "cover_only",
      source_updated_at: "parsed",
      fetched_at: "parsed",
      url: "parsed",
      source_id: "parsed",
      latlng: "parsed",
      contact: "not_provided",
    },
  },
  {
    source: "houseprice",
    label: "5168 租屋",
    fields: {
      address: "parsed",
      community: "parsed",
      floor: "parsed",
      rent: "parsed",
      extra_fees: "partial",
      area: "parsed",
      layout: "parsed",
      kind: "parsed",
      photos: "cover_only",
      source_updated_at: "missing",
      fetched_at: "parsed",
      url: "parsed",
      source_id: "parsed",
      latlng: "parsed",
      contact: "not_provided",
    },
  },
  {
    source: "ddroom",
    label: "租租通",
    fields: {
      address: "parsed",
      community: "missing",
      floor: "parsed",
      rent: "parsed",
      extra_fees: "partial",
      area: "parsed",
      layout: "parsed",
      kind: "parsed",
      photos: "cover_only",
      source_updated_at: "parsed",
      fetched_at: "parsed",
      url: "parsed",
      source_id: "parsed",
      latlng: "not_provided",
      contact: "partial",
    },
  },
  {
    source: "housefun",
    label: "好房網",
    fields: {
      address: "parsed",
      community: "missing",
      floor: "parsed",
      rent: "parsed",
      extra_fees: "partial",
      area: "parsed",
      layout: "parsed",
      kind: "parsed",
      photos: "cover_only",
      source_updated_at: "parsed",
      fetched_at: "parsed",
      url: "parsed",
      source_id: "parsed",
      latlng: "parsed",
      contact: "partial",
    },
  },
  {
    source: "self",
    label: "吉比本站",
    fields: {
      address: "parsed",
      community: "parsed",
      floor: "parsed",
      rent: "parsed",
      extra_fees: "parsed",
      area: "parsed",
      layout: "parsed",
      kind: "parsed",
      photos: "parsed",
      source_updated_at: "parsed",
      fetched_at: "parsed",
      url: "parsed",
      source_id: "parsed",
      latlng: "not_fetched",
      contact: "parsed",
    },
  },
  {
    source: "rakuya",
    label: "樂屋網",
    fields: {
      address: "parsed",
      community: "parsed",
      floor: "parsed",
      rent: "parsed",
      extra_fees: "partial",
      area: "parsed",
      layout: "parsed",
      kind: "partial",
      age: "parsed",
      elevator: "parsed",
      parking: "parsed",
      photos: "cover_only",
      source_updated_at: "parsed",
      fetched_at: "parsed",
      url: "parsed",
      source_id: "parsed",
      latlng: "not_provided",
      contact: "not_provided",
    },
    notes: "公開 HTML／JSON-LD。Cloudflare／驗證視為 FETCH_BLOCKED，不繞過。",
  },
];

export function preferKeptValue(incoming, existing) {
  const next = incoming == null ? "" : incoming;
  const prev = existing == null ? "" : existing;
  if (next === "" || next == null) return prev;
  if (Array.isArray(next) && next.length === 0 && Array.isArray(prev) && prev.length) return prev;
  return incoming;
}

export function fieldStatus(value, { fetched = true, parseFailed = false } = {}) {
  if (parseFailed) return FIELD_STATUS.PARSE_FAILED;
  if (!fetched) return FIELD_STATUS.NOT_FETCHED;
  if (value == null || value === "") return FIELD_STATUS.NOT_PROVIDED;
  return FIELD_STATUS.PARSED;
}
