// sponsor_entitlement 三表的 PostgreSQL 原生 schema（migration v11，開閘 D-0021 批次）。
//
// 為什麼需要它：`sponsorEntitlementAsync.entitlementExec` 原本靠
// `ensurePgSchema(pgDriver, sqliteHandle(), { tables: SPONSOR_ENTITLEMENT_TABLES })` 惰性鏡射建表。
// PG_NO_SQLITE_OPEN=1 後沒有 sqlite handle 可用，鏡射路徑整條會拋。這裡把權威 schema 定義搬到
// PG 側（資料驅動，同 budgetPgSchema.js），並對應 SQLite 側 `sponsorEntitlement.js`
// `ensureSponsorEntitlementSchema()`（migration v11）的同源欄位：
//   INTEGER→BIGINT、REAL→DOUBLE PRECISION、INTEGER PRIMARY KEY AUTOINCREMENT→
//   BIGINT GENERATED BY DEFAULT AS IDENTITY、TEXT PRIMARY KEY→TEXT PRIMARY KEY。
//
// `code`／`support_transaction_id` 的 UNIQUE 在 SQLite 是內聯欄位約束（隱式索引，不在
// sqlite_master），`ensurePgSchema` 鏡射看不到；這裡用內聯 `UNIQUE(...)` 顯式宣告，並保留
// `CREATE UNIQUE INDEX IF NOT EXISTS` 當既有表（legacy 鏡射出來、只有 unique index 沒有
// constraint 的）遷移後盾。
import { quoteIdent } from "./pgSchema.js";

const TEXT = "TEXT";
const BIGINT = "BIGINT";
const DOUBLE = "DOUBLE PRECISION";
const IDENTITY_ID = `${BIGINT} GENERATED BY DEFAULT AS IDENTITY`;

export const SPONSOR_ENTITLEMENT_PG_TABLES = [
  {
    name: "member_support_code",
    identity: "id",
    columns: [
      { name: "id", type: IDENTITY_ID, primaryKey: true },
      { name: "user_id", type: BIGINT, notNull: true },
      { name: "code", type: TEXT, notNull: true },
      { name: "expires_at", type: TEXT, notNull: true },
      { name: "used_at", type: TEXT },
      { name: "created_at", type: TEXT, notNull: true },
    ],
    unique: [["code"]],
    uniqueIndexes: [{ name: "member_support_code_code_uniq", columns: ["code"] }],
    indexes: [["idx_member_support_code_user", ["user_id", "created_at"]]],
  },
  {
    name: "sponsor_entitlement_grant",
    identity: "id",
    columns: [
      { name: "id", type: IDENTITY_ID, primaryKey: true },
      { name: "support_transaction_id", type: TEXT, notNull: true },
      { name: "user_id", type: BIGINT, notNull: true },
      { name: "provider", type: TEXT, notNull: true, default: "''" },
      { name: "amount", type: DOUBLE, notNull: true, default: "0" },
      { name: "reason", type: TEXT, notNull: true, default: "''" },
      { name: "entitlement_expires_at", type: TEXT },
      { name: "created_at", type: TEXT, notNull: true },
    ],
    unique: [["support_transaction_id"]],
    uniqueIndexes: [{ name: "sponsor_entitlement_grant_tx_uniq", columns: ["support_transaction_id"] }],
    indexes: [["idx_sponsor_grant_user", ["user_id", "created_at"]]],
  },
  {
    name: "support_poll_cursor",
    identity: null,
    columns: [
      { name: "provider", type: TEXT, primaryKey: true },
      { name: "cursor_at", type: TEXT, notNull: true },
      { name: "updated_at", type: TEXT, notNull: true },
    ],
    unique: [],
    uniqueIndexes: [],
    indexes: [],
  },
];

function columnDef(column) {
  const parts = [quoteIdent(column.name), column.type];
  if (column.primaryKey) parts.push("PRIMARY KEY");
  if (column.notNull) parts.push("NOT NULL");
  if (column.default != null) parts.push(`DEFAULT ${column.default}`);
  return parts.join(" ");
}

function createTableStatement(table) {
  const lines = table.columns.map((column) => `  ${columnDef(column)}`);
  for (const columns of table.unique) {
    lines.push(`  UNIQUE (${columns.map(quoteIdent).join(", ")})`);
  }
  return `CREATE TABLE IF NOT EXISTS ${quoteIdent(table.name)} (\n${lines.join(",\n")}\n)`;
}

export function sponsorEntitlementPgCreateTableStatements() {
  return SPONSOR_ENTITLEMENT_PG_TABLES.map(createTableStatement);
}

export function sponsorEntitlementPgAddColumnStatements() {
  const statements = [];
  for (const table of SPONSOR_ENTITLEMENT_PG_TABLES) {
    for (const column of table.columns) {
      if (column.primaryKey) continue;
      const def = [
        column.type,
        column.notNull ? "NOT NULL" : "",
        column.default != null ? `DEFAULT ${column.default}` : "",
      ].filter(Boolean).join(" ");
      statements.push(`ALTER TABLE ${quoteIdent(table.name)} ADD COLUMN IF NOT EXISTS ${quoteIdent(column.name)} ${def}`);
    }
  }
  return statements;
}

export function sponsorEntitlementPgIndexStatements() {
  return SPONSOR_ENTITLEMENT_PG_TABLES.flatMap((table) =>
    table.indexes.map(([name, columns]) =>
      `CREATE INDEX IF NOT EXISTS ${quoteIdent(name)} ON ${quoteIdent(table.name)} (${columns.map(quoteIdent).join(", ")})`,
    ),
  );
}

export function sponsorEntitlementPgUniqueIndexStatements() {
  return SPONSOR_ENTITLEMENT_PG_TABLES.flatMap((table) =>
    table.uniqueIndexes.map(({ name, columns }) =>
      `CREATE UNIQUE INDEX IF NOT EXISTS ${quoteIdent(name)} ON ${quoteIdent(table.name)} (${columns.map(quoteIdent).join(", ")})`,
    ),
  );
}

export function sponsorEntitlementPgDdlStatements() {
  return [
    ...sponsorEntitlementPgCreateTableStatements(),
    ...sponsorEntitlementPgAddColumnStatements(),
    ...sponsorEntitlementPgIndexStatements(),
    ...sponsorEntitlementPgUniqueIndexStatements(),
  ];
}

export const SPONSOR_ENTITLEMENT_PG_TABLE_NAMES = SPONSOR_ENTITLEMENT_PG_TABLES.map((table) => table.name);
