// 推播訂閱（web push）的 driver-aware 入口（PG 島嶼，2026-09-27）。
//
// 涵蓋的路由：`POST /api/push/subscribe`、`POST /api/push/unsubscribe`。
//
// ⚠️ 這個小小的模組有一個**會直接壞掉**的坑：同步版的訂閱是
//
//   INSERT INTO push_subscriptions(...) VALUES (...) ON CONFLICT(endpoint) DO UPDATE SET ...
//
// `ON CONFLICT(endpoint)` **要求 endpoint 上有唯一約束**——而 SQLite 的
// `endpoint TEXT NOT NULL UNIQUE` 是**欄位約束**（隱式索引 `sqlite_autoindex_…`），
// 不在 `sqlite_master` 的具名索引裡 ⇒ `pgSchema` 鏡射不到。實測正式站
// `push_subscriptions` **只有 pkey**，所以那句話在 PG 上會直接 `42P10`
// （`there is no unique or exclusion constraint matching the ON CONFLICT specification`）。
//
// 所以 bootstrap 必須先補建 `UNIQUE(endpoint)`——而且**要先清重複**才建得起來
// （同一支手機重複訂閱時，舊資料可能已經有兩列同 endpoint；保留最後看到的那一列，
// 因為 upsert 的語意就是「以最新一次為準」）。
import { resolveDbDriver } from "./dbDriver.js";
import { sqliteFallbackAllowed } from "./sqliteFallback.js";
import { toPostgresSql } from "./sqlDialect.js";
import { httpError, pushSubscriptionFields } from "./webPush.js";

export const PUSH_INSERT_SQL =
  `INSERT INTO push_subscriptions(user_id, endpoint, p256dh, auth, created_at, last_seen_at)
   VALUES (?, ?, ?, ?, ?, ?)
   ON CONFLICT(endpoint) DO UPDATE SET
     user_id = excluded.user_id,
     p256dh = excluded.p256dh,
     auth = excluded.auth,
     last_seen_at = excluded.last_seen_at`; // webPush.js:113
export const PUSH_DELETE_SQL = "DELETE FROM push_subscriptions WHERE user_id = ? AND endpoint = ?"; // webPush.js:128
export const PUSH_LIST_SQL = "SELECT endpoint, p256dh, auth FROM push_subscriptions WHERE user_id = ?"; // webPush.js:133

export const PG_SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS push_subscriptions (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     user_id BIGINT NOT NULL,
     endpoint TEXT NOT NULL,
     p256dh TEXT NOT NULL,
     auth TEXT NOT NULL,
     created_at TEXT NOT NULL,
     last_seen_at TEXT NOT NULL
   )`,
  "CREATE INDEX IF NOT EXISTS idx_push_user ON push_subscriptions(user_id)",
];
// 同步版是欄位約束 `endpoint TEXT NOT NULL UNIQUE`（隱式索引）⇒ PG 這邊要明確補。
export const PG_DUPLICATE_ENDPOINTS_SQL =
  "SELECT endpoint, MAX(id) AS keep_id FROM push_subscriptions GROUP BY endpoint HAVING COUNT(*) > 1";
export const PG_DROP_DUPLICATE_ENDPOINT_SQL =
  "DELETE FROM push_subscriptions WHERE endpoint = ? AND id <> ?";
export const PG_CREATE_ENDPOINT_INDEX_SQL =
  "CREATE UNIQUE INDEX IF NOT EXISTS push_subscriptions_endpoint_key ON push_subscriptions(endpoint)";

const isPg = (options = {}) => (options.driver || resolveDbDriver()) === "postgres";

async function pgExec(options = {}) {
  if (options.exec) return options.exec;
  const pgDriver = options.pgDriver || (await (await import("./pgSharedDriver.js")).sharedPgDriver());
  return (sql, params = []) => pgDriver.query(toPostgresSql(sql), params).then((res) => res.rows);
}

const schemaReady = new WeakMap();
export async function ensurePushStoreOnce(pgDriver) {
  if (!pgDriver) return;
  if (schemaReady.has(pgDriver)) return schemaReady.get(pgDriver);
  const ready = (async () => {
    for (const sql of PG_SCHEMA_STATEMENTS) await pgDriver.exec(sql);
    // 先清重複（保留 id 最大的那一列＝最後寫入的那一次）再建唯一索引，
    // 否則有重複時 CREATE UNIQUE INDEX 會直接失敗、整個 bootstrap 掛掉。
    const dupes = await pgDriver.query(PG_DUPLICATE_ENDPOINTS_SQL);
    for (const row of dupes.rows) {
      await pgDriver.query(toPostgresSql(PG_DROP_DUPLICATE_ENDPOINT_SQL), [row.endpoint, row.keep_id]);
    }
    await pgDriver.exec(PG_CREATE_ENDPOINT_INDEX_SQL);
  })();
  schemaReady.set(pgDriver, ready);
  try {
    await ready;
  } catch (error) {
    schemaReady.delete(pgDriver);
    throw error;
  }
}

async function withFallback(options, runPostgres, runSqlite) {
  if (!isPg(options)) return runSqlite();
  try {
    return await runPostgres();
  } catch (error) {
    if (!sqliteFallbackAllowed(options, { write: true })) throw error;
    return runSqlite();
  }
}

const syncWebPush = () => import("./webPush.js");
const syncDb = () => import("./db.js");

export async function savePushSubscriptionAsync(userId, sub = {}, options = {}) {
  const uid = Number(userId) || 0;
  if (!uid) throw httpError("請先登入", 401);
  if (!isPg(options)) {
    const { saveUserPushSubscription } = await syncDb();
    return saveUserPushSubscription(uid, sub);
  }
  // 純驗證，兩邊共用同一份（`pushSubscriptionFields`）。
  const { endpoint, p256dh, auth } = pushSubscriptionFields(sub);
  const now = new Date().toISOString();
  return withFallback(options, async () => {
    const exec = await pgExec(options);
    if (!options.exec) await ensurePushStoreOnce(options.pgDriver || (await (await import("./pgSharedDriver.js")).sharedPgDriver()));
    await exec(PUSH_INSERT_SQL, [uid, endpoint, p256dh, auth, now, now]);
    return { ok: true };
  }, async () => {
    const { saveUserPushSubscription } = await syncDb();
    return saveUserPushSubscription(uid, sub);
  });
}

export async function deletePushSubscriptionAsync(userId, endpoint, options = {}) {
  const uid = Number(userId) || 0;
  const url = String(endpoint || "").trim();
  if (!uid || !url) return { ok: true }; // 與同步版同義：缺參數就直接回 ok
  if (!isPg(options)) {
    const { deleteUserPushSubscription } = await syncDb();
    return deleteUserPushSubscription(uid, url);
  }
  return withFallback(options, async () => {
    const exec = await pgExec(options);
    if (!options.exec) await ensurePushStoreOnce(options.pgDriver || (await (await import("./pgSharedDriver.js")).sharedPgDriver()));
    await exec(PUSH_DELETE_SQL, [uid, url]);
    return { ok: true };
  }, async () => {
    const { deleteUserPushSubscription } = await syncDb();
    return deleteUserPushSubscription(uid, url);
  });
}

export async function listPushSubscriptionsAsync(userId, options = {}) {
  const uid = Number(userId) || 0;
  if (!isPg(options)) return (await syncWebPush()).listPushSubscriptions((await import("./db.js")).sqliteHandle(), uid);
  const exec = await pgExec(options);
  if (!options.exec) await ensurePushStoreOnce(options.pgDriver || (await (await import("./pgSharedDriver.js")).sharedPgDriver()));
  return exec(PUSH_LIST_SQL, [uid]);
}
