name: 591-tracker

services:
  591-tracker:
    container_name: 591-tracker
    build: .
    image: 591-tracker:latest
    restart: unless-stopped
    ports:
      - "5151:5151"
    environment:
      HOST: "0.0.0.0"
      PORT: "5151"
      DATA_DIR: /data
      TZ: Asia/Taipei
    volumes:
      - ${DATA_ROOT:-/DATA}/AppData/591-tracker:/data
