import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dir = path.dirname(fileURLToPath(import.meta.url));
const html = readFileSync(path.join(dir, "../public/console.html"), "utf8");
const js = readFileSync(path.join(dir, "../public/console.js"), "utf8");
const css = readFileSync(path.join(dir, "../public/console.css"), "utf8");

test("console eats local kit tokens instead of a remote design host", () => {
  assert.match(html, /href="\/kit\/tokens\.css"/);
  assert.match(html, /href="\/kit\/themes\/ops\.css"/);
  assert.match(html, /href="\/kit\/components\.css"/);
  assert.doesNotMatch(html, /https?:\/\/[^"']+\/(?:kit|tokens\.css)/);
  assert.doesNotMatch(css, /localhost:5154/);
});

test("console covers inbox, issues, gates and webhook test", () => {
  assert.match(html, /回饋收件匣/);
  assert.match(html, /議題與投票/);
  assert.match(html, /核准開發/);
  assert.match(html, /測試 webhook/);
  assert.doesNotMatch(html, /Phase 1（骨架/);
  assert.match(js, /\/ops\/api\/dashboard/);
  assert.match(js, /\/ops\/api\/feedback/);
  assert.match(js, /\/ops\/api\/notify\/test/);
  assert.match(html, /APPROVE_DEVELOPMENT/);
});

test("tab panes honor the hidden attribute (display:grid must not override it)", () => {
  assert.match(css, /\.tabpane\[hidden\]\s*\{[^}]*display:\s*none\s*!important/);
  assert.match(css, /#ownerArea\[hidden\]\s*\{[^}]*display:\s*none\s*!important/);
  assert.match(js, /pane\.hidden = pane\.id !== `tab-\$\{name\}`/);
  assert.match(html, /id="tab-inbox"[^>]*hidden/);
  assert.match(html, /id="tab-issues"[^>]*hidden/);
  assert.match(html, /id="tab-audit"[^>]*hidden/);
  assert.match(html, /id="tab-products"[^>]*hidden/);
  assert.match(html, /id="tab-crm"[^>]*hidden/);
  assert.match(html, /id="tab-dev"[^>]*hidden/);
  assert.match(html, /data-tab="dev"/);
  assert.match(html, /data-tab="providers"/);
  assert.match(html, /id="tab-providers"[^>]*hidden/);
  assert.match(js, /refreshProviders/);
  assert.match(js, /DRAWER_CODE_LABEL/);
  assert.match(js, /儲存中/);
  assert.match(html, /aria-controls="tab-dev"/);
  assert.match(html, /id="tab-dev"[^>]*role="tabpanel"/);
  assert.match(js, /tabindex="0"/);
  assert.match(js, /aria-selected/);
  assert.match(js, /aria-busy/);
  assert.match(js, /確認重佈隔離 staging/);
  assert.match(js, /devCancelStg"\)\.disabled/);
  assert.match(js, /讀取失敗/);
  assert.match(html, /開發發行/);
  assert.match(html, /隔離 staging/);
  assert.match(html, /核准發布授權/);
  assert.match(html, /停止測試容器/);
  assert.match(html, /不會部署正式機/);
  assert.match(js, /\/ops\/api\/coding-tasks/);
  assert.match(js, /\/ops\/api\/coding-tasks\/\$\{id\}\/staging/);
  assert.match(js, /\/ops\/api\/coding-tasks\/\$\{id\}\/release/);
  assert.match(js, /\/ops\/api\/coding-tasks\/\$\{id\}\/qa/);
  assert.match(js, /qa\/rerun/);
  assert.match(js, /issue_title/);
  assert.match(js, /openOwnerQueueItem/);
  assert.match(js, /focusHeading/);
  assert.match(js, /hasLatestDecision/);
  assert.match(js, /latest_decision/);
  assert.match(js, /closeDevDetail/);
  assert.match(js, /待辦無法載入/);
  assert.match(js, /data-gate/);
  assert.match(js, /WAITING_RELEASE_APPROVAL/);
  assert.match(html, /tabindex="-1"/);
  assert.match(html, /devRerunQa/);
  assert.match(html, /獨立 QA/);
  assert.match(css, /\.queue-item/);
  assert.match(css, /\.tbl-wrap/);
  assert.match(css, /\[hidden\]\s*\{[^}]*display:\s*none\s*!important/);
  assert.match(js, /APPROVE_RELEASE/);
  assert.match(js, /cleanup/);
  assert.match(js, /正式站無感/);
  assert.match(js, /測試站已到期，可重建相同版本/);
  assert.match(js, /此網址目前是/);
  assert.match(js, /reasonRequired/);
  assert.match(js, /請說明要改什麼/);
  assert.match(js, /issueFollowUp/);
  assert.match(js, /建立後續開發/);
  assert.match(html, /confirmReason/);
  assert.match(html, /issueFollowUp/);
  assert.match(html, /follow-up|後續開發/);
  assert.match(js, /\/ops\/api\/production-releases\/\$\{id\}\/cancel/);
  assert.match(js, /\/ops\/api\/production-releases\/\$\{id\}\/cancel-runner/);
  assert.doesNotMatch(js, /\/ops\/api\/production-releases\/\$\{id\}\/(execute|rollback|retry|reconcile)/);
  assert.match(html, /data-tab="crm"/);
  assert.match(html, /四欄分開/);
  assert.match(js, /\/ops\/api\/crm/);
  assert.match(js, /前往本站處理/);
  assert.match(js, /尚未設定本站後台網址/);
  assert.match(js, /function publicSiteAdminHref/);
  assert.match(js, /&quot;/);
  assert.match(js, /請先選單一站台再開關模組/);
  assert.match(css, /\.crm-url-form/);
  assert.match(js, /Owner 商務備註/);
  assert.match(js, /crm_sync/);
  assert.match(js, /revoke-crm-sync/);
  assert.match(js, /grant-remote-cs/);
  assert.match(js, /遠端客服關閉/);
  assert.match(js, /\/ops\/api\/site-commands/);
  assert.match(html, /遠端客服預設關/);
  assert.match(js, /grant-insight/);
  assert.match(html, /跨站分析、統計指標、後續服務預設關/);
  assert.match(html, /晚到的分析、評估、提案、自動重評、製作／QA、遠端客服/);
  assert.match(html, /隔離 staging/);
  assert.match(html, /正式部署狀態不明時，先確認該環境實際結果，再完成移交/);
  assert.match(js, /正式部署狀態不明時會拒絕移交/);
  assert.match(js, /grant-stats/);
  assert.match(js, /grant-followup/);
  assert.match(js, /統計指標未授權|指標不含未授權站/);
  assert.match(js, /setProductCapability/);
  assert.match(js, /授權紀錄/);
  assert.match(js, /案件：/);
  assert.match(js, /crmHandlingLabel/);
  assert.match(js, /classList\.toggle\("danger"/);
  assert.match(js, /請先選單一站台再授權/);
  assert.match(css, /\.crm-cols/);
  assert.match(css, /@media \(max-width: 520px\)/);
  assert.match(html, /console\.css\?v=/);
  assert.match(html, /console\.js\?v=/);
});

test("console has product cards, switcher, and one-time secret", () => {
  assert.match(html, /data-tab="products"/);
  assert.match(html, /產品卡/);
  assert.match(html, /id="productCards"/);
  assert.match(html, /id="productSwitch"/);
  assert.match(html, /id="secretOnce"[^>]*hidden/);
  assert.match(html, /只顯示一次/);
  assert.match(html, /id="confirmDlg"[^>]*hidden/);
  assert.match(html, /role="status"/);
  assert.match(js, /\/ops\/api\/products/);
  assert.match(js, /\/ops\/api\/products\/\$\{encodeURIComponent\(id\)\}\/\$\{action\}/);
  assert.match(js, /pause|resume|unsubscribe|reconnect|rotate-credential/);
  assert.match(js, /確定暫停/);
  assert.match(js, /確定恢復/);
  assert.match(js, /確定解除/);
  assert.match(js, /確定輪替/);
  assert.match(js, /確定重連/);
  assert.match(js, /確定移交/);
  assert.match(js, /confirmChrome/);
  assert.match(js, /trapConfirmTab/);
  assert.match(js, /confirmReturnFocus/);
  assert.match(js, /aria-busy/);
  assert.match(js, /role.*alert/);
  assert.match(js, /使用中/);
  assert.match(js, /aria-label/);
  assert.match(js, /productId=/);
  assert.match(html, /移交整站/);
  assert.match(html, /刪除 OPS 複本/);
  assert.match(js, /handoff|purge-replica|pending/);
  assert.match(js, /EXIT_ACTION_LABEL/);
  assert.match(js, /PENDING_KIND_LABEL/);
  assert.match(js, /移交整站/);
  assert.match(js, /PURGE-\$/);
  assert.match(css, /overflow-x:\s*hidden/);
  assert.match(css, /:focus-visible/);
  assert.match(html, /aria-live="polite"/);
});
