// 升級層 D-0021 首包：budget store 的 PG 原生 schema（拆掉「PG 靠 SQLite handle 建表」的硬相依）。
//
// 兩段：
//   1. 原生路徑（不傳 sqliteDb）：ensureBudgetStoreOnce(pgDriver) 只靠 PG 側 DDL 就成功，
//      實際發出的語句要含 identity 欄、內聯 UNIQUE 約束、唯一索引後盾與 setval 序號對齊。
//   2. legacy 路徑（有 sqliteDb）：仍走原本的鏡射（ensurePgSchema＋唯一索引＋resyncIdentitySequences），
//      行為逐字不變（不回退到原生 DDL）。
//   3. live（PG_BUDGET_TEST_URL）：證明「帶 id 匯入後，下一筆不帶 id 的自增寫入不撞主鍵」。
import { test } from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";

const budget = await import("../src/budgetGuard.js");
const budgetAsync = await import("../src/budgetGuardAsync.js");
const budgetPgSchema = await import("../src/budgetPgSchema.js");

function fakePgDriver() {
  const exec = [];
  const query = [];
  return {
    exec: async (sql) => { exec.push(String(sql)); },
    query: async (sql, _params = []) => { query.push(String(sql)); return { rows: [] }; },
    _exec: exec,
    _query: query,
  };
}

test("原生路徑：ensureBudgetStoreOnce(pgDriver) 不傳 sqliteDb 也能建表＋補 UNIQUE＋對齊序號", async () => {
  const fake = fakePgDriver();
  await budgetAsync.ensureBudgetStoreOnceForTest(fake);
  const ddl = fake._exec;
  const resync = fake._query;

  // 五張表都要 CREATE TABLE IF NOT EXISTS。
  for (const name of budgetPgSchema.BUDGET_PG_TABLE_NAMES) {
    assert.ok(
      ddl.some((sql) => sql.includes(`CREATE TABLE IF NOT EXISTS ${name}`)),
      `應有 ${name} 的 CREATE TABLE IF NOT EXISTS`,
    );
  }
  // identity 欄：四張有 id 的表都要 GENERATED BY DEFAULT AS IDENTITY。
  assert.ok(ddl.filter((sql) => sql.includes("BIGINT GENERATED BY DEFAULT AS IDENTITY")).length >= 4);

  // 內聯 UNIQUE 約束（SQLite 鏡射補不到的三個）。
  const inlineUnique = ddl.filter((sql) => /UNIQUE\s*\(/.test(sql) && sql.startsWith("CREATE TABLE"));
  assert.equal(inlineUnique.length, 3, "三張表要有內聯 UNIQUE(...) 約束");
  // 唯一索引後盾（沿用正式庫現有三個名字）。
  assert.equal(
    ddl.filter((sql) => sql.includes("CREATE UNIQUE INDEX IF NOT EXISTS")).length,
    3,
    "要有三個唯一索引後盾",
  );

  // 序號對齊：四張 identity 表各一條 setval(pg_get_serial_sequence(...), max(id)+1)。
  assert.equal(
    resync.filter((sql) => sql.includes("setval") && sql.includes("pg_get_serial_sequence")).length,
    4,
    "四張 identity 表都要對齊序號",
  );
});

test("legacy 路徑：有 sqliteDb 時仍走鏡射（不回退原生 DDL、行為不變）", async () => {
  const sqlite = new DatabaseSync(":memory:");
  sqlite.exec("CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL)");
  budget.ensureBudgetSchema(sqlite);

  const fake = fakePgDriver();
  await budgetAsync.ensureBudgetStoreOnceForTest(fake, sqlite);
  const ddl = fake._exec;
  const resync = fake._query;

  // 鏡射路徑的 CREATE TABLE 不含內聯 UNIQUE（那是 pgSchema 鏡射看不到的隱式索引）。
  assert.equal(
    ddl.filter((sql) => sql.startsWith("CREATE TABLE") && /UNIQUE\s*\(/.test(sql)).length,
    0,
    "鏡射路徑的建表不應有內聯 UNIQUE（由唯一索引補）",
  );
  // 唯一索引照舊由 BUDGET_UNIQUE_INDEXES 補上。
  assert.equal(ddl.filter((sql) => sql.includes("CREATE UNIQUE INDEX IF NOT EXISTS")).length, 3);
  // 序號對齊照舊由 resyncIdentitySequences 發 setval。
  assert.equal(resync.filter((sql) => sql.includes("setval")).length, 4);
  sqlite.close();
});

test("live：帶 id 匯入後下一筆自增不撞主鍵（PG_BUDGET_TEST_URL）", async (t) => {
  const url = process.env.PG_BUDGET_TEST_URL;
  if (!url) {
    t.skip("PG_BUDGET_TEST_URL is not set (native sequence alignment live test)");
    return;
  }
  const { createPostgresDriver } = await import("../src/dbDriverPostgres.js");
  const driver = await createPostgresDriver({ connectionString: url });
  const importedId = 800_000_000 + Math.floor(Math.random() * 1_000_000);
  const runId = `budget-native-${Date.now()}`;
  try {
    for (const statement of budgetPgSchema.budgetPgDdlStatements()) await driver.exec(statement);

    // 模擬「帶 id 的匯入」：直接塞一筆高 id（不推進 identity 序號）。
    await driver.query(
      "INSERT INTO call_reservations(id, request_id, attempt_id, ceiling_minor, job_state, created_at) VALUES ($1, $2, $3, 0, 'settled', now())",
      [importedId, runId, "a1"],
    );

    // 原生初始化裡的序號對齊。
    for (const statement of budgetPgSchema.budgetPgIdentityResyncStatements()) await driver.query(statement);

    // 下一筆不帶 id 的自增寫入不可撞主鍵。
    const inserted = await driver.query(
      "INSERT INTO call_reservations(request_id, attempt_id, ceiling_minor, job_state, created_at) VALUES ($1, $2, 0, 'reserved', now()) RETURNING id",
      [`${runId}-2`, "a1"],
    );
    const autoId = Number(inserted.rows[0].id);
    assert.ok(autoId > importedId, `自增 id ${autoId} 必須越過匯入的最大 id ${importedId}`);
  } finally {
    try {
      await driver.query("DELETE FROM call_reservations WHERE request_id = ANY($1::text[])", [[runId, `${runId}-2`]]);
    } catch { /* 清不掉不影響斷言 */ }
    await driver.close();
  }
});
