// 2026-09-24 Production 事故的回歸測試。
//
// PG 的 store 是「帶 id 匯入」的，PostgreSQL 不會因為帶 id 的 INSERT 推進
// GENERATED BY DEFAULT AS IDENTITY 序號 → data_revision 表內 max(id)=685489、序號卻停在 305，
// 每一次 bumpRevision 都撞 data_revision_pkey。PG 路徑的 bump 是 await 的，於是那一輪抓取
// 整輪中止（crawl_covers.last_run_at 永遠 NULL、events 24 小時 0 筆、每小時只檢查約 20 筆）。
//
// 這支測試釘住兩件事：
//   1) PG 路徑在第一次寫入前就把 data_revision 的 identity 序號對齊；
//   2) 變更紀錄是輔助資料，它失敗不可以讓 persistListing() 拋出。
import { after, test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { DATA_REVISION_DDL } from "../src/dataRevision.js";
import { identityResyncSql, resyncIdentitySequences } from "../src/pgSchema.js";

const dataDir = mkdtempSync(path.join(os.tmpdir(), "v3-change-log-"));
process.env.DATA_DIR = dataDir;
after(() => {
  try {
    rmSync(dataDir, { recursive: true, force: true });
  } catch {
    // Windows keeps the SQLite file locked while the process holds it.
  }
});

function memorySqlite() {
  const db = new DatabaseSync(":memory:");
  db.exec(DATA_REVISION_DDL);
  db.exec("CREATE TABLE other_table (id TEXT PRIMARY KEY, note TEXT)");
  return db;
}

const insertRevision = (db, id, entityId = 1) => db.prepare(
  "INSERT INTO data_revision (id, entity_type, entity_id, event_type, created_at) VALUES (?, ?, ?, ?, ?)",
).run(id, "listing", entityId, "listing_added", 1);

function fakePgDriver({ onQuery = null } = {}) {
  const calls = [];
  const driver = {
    calls,
    async exec(sql) {
      calls.push({ kind: "exec", sql });
    },
    async query(sql, params = []) {
      calls.push({ kind: "query", sql, params });
      if (onQuery) onQuery(sql, params);
      return { rows: [], rowCount: 0 };
    },
    // persistListing 於 PR-B 起把主列／投影／變更紀錄包在同一交易（PR-B F7/G9）→ 假 driver 也要支援。
    async withTransaction(fn) {
      calls.push({ kind: "begin", sql: "BEGIN" });
      const client = {
        query: (sql, params = []) => driver.query(sql, params),
        connect: () => client,
      };
      try {
        const result = await fn(client);
        calls.push({ kind: "commit", sql: "COMMIT" });
        return result;
      } catch (error) {
        calls.push({ kind: "rollback", sql: "ROLLBACK" });
        throw error;
      }
    },
  };
  return driver;
}

test("data_revision 的序號校正 SQL 對齊 max(id) + 1（且不會把領先的序號調低）", () => {
  const sqlite = memorySqlite();
  insertRevision(sqlite, 11);
  insertRevision(sqlite, 685489);
  const sql = identityResyncSql(sqlite, "data_revision");
  assert.match(sql, /pg_get_serial_sequence\('data_revision', 'id'\)/);
  assert.match(sql, /COALESCE\(\(SELECT MAX\((\"?)id\1\) FROM \"?data_revision\"?\), 0\) \+ 1/);
  assert.match(sql, /, false\)$/);
});

test("resyncIdentitySequences 只校正真的有 auto id 的表", async () => {
  const sqlite = memorySqlite();
  insertRevision(sqlite, 7);
  const driver = fakePgDriver();
  const synced = await resyncIdentitySequences(driver, sqlite, { tables: ["data_revision", "other_table"] });
  assert.deepEqual(synced, ["data_revision"]);
  assert.equal(driver.calls.length, 1);
  assert.match(driver.calls[0].sql, /setval\(/);
});

test("PG 路徑：變更紀錄失敗時 persistListing() 仍成功，且事前已校正序號", async () => {
  const app = await import("../src/db.js");
  const driver = fakePgDriver({
    onQuery: (sql) => {
      if (/INSERT INTO data_revision/i.test(sql)) {
        throw new Error('duplicate key value violates unique constraint "data_revision_pkey"');
      }
    },
  });
  const warnings = [];
  const originalWarn = console.warn;
  console.warn = (...args) => {
    warnings.push(args.join(" "));
  };
  let result;
  try {
    result = await app.persistListing({
      post_id: 9_400_001,
      source: "591",
      source_id: "9400001",
      source_key: "1|8|9400001",
      search_key: "https://example.test/search",
      title: "變更紀錄失敗的回歸測試",
      url: "https://example.test/listing/9400001",
      price: "25000元",
      price_num: 25000,
      extra_fee: 0,
      extra_fees: [],
      tags: "[]",
      first_seen_at: "2026-09-24T00:00:00.000Z",
      last_seen_at: "2026-09-24T00:00:00.000Z",
      last_event: "new",
    }, { driver: "postgres", pgDriver: driver });
  } finally {
    console.warn = originalWarn;
  }
  assert.equal(result.driver, "postgres");

  const resyncAt = driver.calls.findIndex(
    (call) => call.kind === "query" && /setval\(pg_get_serial_sequence\('data_revision'/.test(call.sql),
  );
  const bumpAt = driver.calls.findIndex((call) => /INSERT INTO data_revision/i.test(call.sql));
  assert.ok(resyncAt >= 0, "第一次 PG 寫入前就該送 data_revision 的序號校正");
  assert.ok(bumpAt > resyncAt, "序號校正必須在變更紀錄寫入之前");
  assert.ok(
    warnings.some((line) => line.includes("變更紀錄寫入失敗")),
    "變更紀錄失敗要留下警告，而不是靜默或往外拋",
  );
});
