// dataRevisionAsync 開閘（PG_NO_SQLITE_OPEN=1）下的讀取路徑（2026-10-09）。
//
// 釘住 L-0445 的修法：`ensureDataRevisionStoreOnce`／`currentRevisionAsync`／`changesSinceAsync`
// 在 PG 模式下不得再拿 `sqliteHandle()` 當可用 handle（truthy 的拋錯 proxy），要用
// `sqliteHandleIsUsable()` 判；不可用時走 PG 原生 DDL＋序號對齊。目標端點
// `/api/events/revision` 在開閘下要回 200＋正確 revision（這裡直接驅動 `currentRevisionAsync`
// 並注入 fake pgDriver，繞過需要真實 PG 連線的 sharedPgDriver）。
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { spawnSync } from "node:child_process";
import os from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const dir = path.dirname(fileURLToPath(import.meta.url));
const ISOLATED_TIMEOUT_MS = Math.max(30_000, Number(process.env.V3_ISOLATED_TEST_TIMEOUT_MS) || 180_000);

test("開閘下 currentRevisionAsync 走 PG 原生路徑（不回退、不碰 SQLite proxy）", () => {
  const dataDir = mkdtempSync(path.join(os.tmpdir(), "v3-datarev-gate-"));
  const script = `
    const dbMod = await import(${JSON.stringify(pathToFileURL(path.join(dir, "../src/db.js")).href)});
    const asyncMod = await import(${JSON.stringify(pathToFileURL(path.join(dir, "../src/dataRevisionAsync.js")).href)});

    // 開閘時 sqliteHandle() 是帶 marker 的拋錯 proxy：碰任何 method 都會拋。
    let touchedSqlite = false;
    try { dbMod.sqliteHandle().prepare("SELECT 1").get(); } catch (e) { touchedSqlite = /business SQLite is closed/.test(e.message); }

    const ddl = [];
    const queries = [];
    const fakePg = {
      exec: async (sql) => { ddl.push(String(sql)); },
      query: async (sql) => { queries.push(String(sql)); return { rows: [{ n: 42 }], rowCount: 1 }; },
    };

    const rev = await asyncMod.currentRevisionAsync({ driver: "postgres", pgDriver: fakePg, strict: true });
    const changes = await asyncMod.changesSinceAsync(0, { limit: 500 }, { driver: "postgres", pgDriver: fakePg, strict: true });

    const create = ddl.find((sql) => /^CREATE TABLE/i.test(sql)) || "";
    console.log(JSON.stringify({
      touchedSqlite,
      rev,
      changesLength: Array.isArray(changes) ? changes.length : -1,
      createHasRevision: /data_revision/.test(create),
      createIsPgIdentity: /GENERATED BY DEFAULT AS IDENTITY/i.test(create),
      ddlCount: ddl.length,
    }));
  `;
  try {
    const result = spawnSync(process.execPath, ["--input-type=module", "-e", script], {
      encoding: "utf8",
      timeout: ISOLATED_TIMEOUT_MS,
      env: { ...process.env, DATA_DIR: dataDir, DB_DRIVER: "postgres", PG_NO_SQLITE_OPEN: "1" },
    });
    assert.equal(result.status, 0, result.error?.message || result.stderr || result.stdout);
    const out = JSON.parse(result.stdout.trim().split("\n").filter((row) => row.startsWith("{")).at(-1));
    assert.equal(out.touchedSqlite, true, "前置條件：開閘下同步 sqliteHandle().prepare 應拋 business SQLite is closed");
    assert.equal(out.rev, 42, "revision 要來自 PG（fake pgDriver 回 42）");
    assert.equal(out.changesLength, 1, "changesSince 也要走 PG");
    assert.equal(out.createHasRevision, true, "PG 原生 DDL 要建 data_revision");
    assert.equal(out.createIsPgIdentity, true, "開閘要走 PG 原生 identity DDL（不是 SQLite 鏡射）");
    assert.ok(out.ddlCount >= 1, "要走 PG 原生 DDL（exec）");
  } finally {
    rmSync(dataDir, { recursive: true, force: true });
  }
});
