// sqlite-exit 批次 C：data_revision 變更紀錄的 PG 原生 schema（拆掉「PG 靠 SQLite handle 建表」的硬相依）。
//
// 兩段：
//   1. 原生路徑（不傳 sqlite handle）：ensureChangeLogStoreOnce(pgDriver) 只靠 PG 側 DDL 就成功，
//      發出的語句要含 identity 欄、非唯一索引後盾與 setval 序號對齊，且不得出現 sqlite_master。
//   2. legacy 路徑（有 sqliteDb）：仍走原本的鏡射（ensurePgSchema＋resyncIdentitySequences），
//      行為逐字不變（不回退到原生 DDL）。
//   3. 下架掃描（watcher.sweepOfflineListings）：開閘後不再同步讀 getSystemCrawl()，
//      改吃 runWatch 已從 PG 載好的 runtime.system（source anchor 釘住形狀）。
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import { mkdtempSync, rmSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { DSH_NO_OPEN_MARKER } from "../src/sqliteHandle.js";
import { DATA_REVISION_DDL } from "../src/dataRevision.js";
import { dataRevisionPgDdlStatements, dataRevisionPgIdentityResyncStatements } from "../src/dataRevisionPgSchema.js";

const dir = path.dirname(fileURLToPath(import.meta.url));
const dataDir = mkdtempSync(path.join(os.tmpdir(), "v3-drev-native-"));
process.env.DATA_DIR = dataDir;

const app = await import("../src/db.js");

// 與 db.js 的 createNoOpenSqliteProxy 同形的開閘 proxy（帶不可枚舉 marker、碰 method 就拋）。
function noOpenProxy() {
  const target = function sqliteClosed() {};
  Object.defineProperty(target, DSH_NO_OPEN_MARKER, { value: true });
  return new Proxy(target, {
    get(_target, prop) {
      if (prop === "then" || prop === "catch" || prop === "finally" || prop === "inspect") return undefined;
      if (typeof prop === "symbol") return undefined;
      return () => {
        throw new Error(`business SQLite is closed (PG_NO_SQLITE_OPEN=1, DB_DRIVER=postgres): synchronous SQLite handle access "${String(prop)}"`);
      };
    },
    apply() {
      throw new Error("business SQLite is closed (PG_NO_SQLITE_OPEN=1, DB_DRIVER=postgres): synchronous SQLite handle was invoked");
    },
  });
}

function fakePgDriver() {
  const exec = [];
  const query = [];
  return {
    exec: async (sql) => { exec.push(String(sql)); },
    query: async (sql, _params = []) => { query.push(String(sql)); return { rows: [] }; },
    _exec: exec,
    _query: query,
  };
}

test("原生路徑：ensureChangeLogStoreOnce 不傳 sqlite handle 也能建表＋索引＋對齊序號", async () => {
  const fake = fakePgDriver();
  await app.ensureChangeLogStoreOnceForTest(fake, noOpenProxy());
  const ddl = fake._exec;
  const resync = fake._query;

  assert.ok(
    ddl.some((sql) => sql.includes("CREATE TABLE IF NOT EXISTS data_revision")),
    "應有 data_revision 的 CREATE TABLE IF NOT EXISTS",
  );
  assert.ok(
    ddl.some((sql) => sql.includes("BIGINT GENERATED BY DEFAULT AS IDENTITY")),
    "id 應是 identity 欄（BIGINT GENERATED BY DEFAULT AS IDENTITY）",
  );
  assert.ok(
    ddl.some((sql) => sql.includes("CREATE INDEX IF NOT EXISTS idx_data_revision_id")),
    "應有 idx_data_revision_id 的非唯一索引",
  );
  assert.equal(
    resync.filter((sql) => sql.includes("setval") && sql.includes("pg_get_serial_sequence")).length,
    1,
    "要對齊一筆 identity 序號",
  );

  const allSql = [...ddl, ...resync].join("\n");
  assert.ok(!allSql.includes("sqlite_master"), "PG 原生路徑不得出現 sqlite_master");
});

test("legacy 路徑：有 sqliteDb 時仍走鏡射（不回退原生 DDL、行為不變）", async () => {
  const sqlite = new DatabaseSync(":memory:");
  sqlite.exec(DATA_REVISION_DDL);
  const fake = fakePgDriver();
  await app.ensureChangeLogStoreOnceForTest(fake, sqlite);
  sqlite.close();
  const ddl = fake._exec;
  const resync = fake._query;

  // 鏡射路徑（ensurePgSchema）會發建表＋索引，且序號對齊照舊由 resyncIdentitySequences 發 setval。
  assert.ok(
    ddl.some((sql) => sql.includes("CREATE TABLE IF NOT EXISTS data_revision")),
    "鏡射路徑應有 data_revision 的建表",
  );
  assert.equal(resync.filter((sql) => sql.includes("setval")).length, 1, "鏡射路徑也要對齊一筆序號");
});

test("下架掃描：開閘後改吃 runtime.system＋confirmExpiredOfflineAsync（不再同步讀寫 SQLite）", () => {
  const watcher = readFileSync(path.join(dir, "../src/watcher.js"), "utf8");
  assert.match(watcher, /system: runtime\.system/, "runWatch 要把已載好的 runtime.system 傳給下架掃描");
  assert.match(watcher, /const systemCrawl = system \|\| await getSystemCrawlAsync\(\);/, "下架掃描要優先吃傳入的 system，沒有時走 async 讀");
  assert.doesNotMatch(watcher, /getSystemCrawl\(\)\.offlineConfirmDays/, "開閘後不得再同步讀 getSystemCrawl()");
  assert.match(watcher, /await confirmExpiredOfflineAsync\(\{ days: confirmDays \}\)/, "確認下線的同步 UPDATE 要改走 driver-aware 的 confirmExpiredOfflineAsync");
  assert.doesNotMatch(watcher, /confirmExpiredOfflineListings\(confirmDays\)/, "不得再用同步版 confirmExpiredOfflineListings（開閘會碰 db.prepare）");
});

test("原生 DDL 與序號對齊語句的形狀（逐字對齊正式庫結構）", () => {
  const ddl = dataRevisionPgDdlStatements();
  const resync = dataRevisionPgIdentityResyncStatements();

  assert.equal(ddl.length, 2, "DDL 應為建表＋索引兩句");
  assert.match(ddl[0], /CREATE TABLE IF NOT EXISTS data_revision/);
  assert.match(ddl[0], /id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  assert.match(ddl[0], /entity_type TEXT NOT NULL/);
  assert.match(ddl[0], /entity_id BIGINT/);
  assert.match(ddl[0], /event_type TEXT NOT NULL/);
  assert.match(ddl[0], /created_at BIGINT NOT NULL/);
  assert.match(ddl[1], /CREATE INDEX IF NOT EXISTS idx_data_revision_id ON data_revision \(id\)/);

  assert.equal(resync.length, 1);
  assert.match(resync[0], /setval\(pg_get_serial_sequence\('data_revision', 'id'\)/);
  assert.match(resync[0], /, false\)$/);
});
