// 使用者回饋（PG 島嶼）的 parity（2026-09-28，第五十八批）。
//
// 涵蓋：`POST /api/feedback`、`GET /api/admin/feedback`、`PATCH /api/admin/feedback/:id`。
//
// 🚨 這一支最重要的是那個**不變式**：「一筆成功寫入的 feedback ⇔ 一筆初始 outbox 事件」。
// 同步版用 `BEGIN IMMEDIATE` 包住兩句 INSERT；PG 版**必須用真的交易**，因為
// `pgDriver.query()` 每句都是自己的隱含交易 —— 分兩句寫就會出現「回饋進去了、事件沒進去」
// 的半套狀態，而那個事件是 Ops 唯一的來源（而且不會有任何錯誤）。
// 下面第 2 條測試用一個「outbox 一定失敗」的觸發器把交易的回滾釘死。
import { after, test } from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdtempSync, rmSync } from "node:fs";
import os from "node:os";
import path from "node:path";

const dataDir = mkdtempSync(path.join(os.tmpdir(), "v3-feedback-"));
process.env.DATA_DIR = dataDir;
after(() => { try { rmSync(dataDir, { recursive: true, force: true }); } catch { /* Windows lock */ } });

const dbMod = await import("../src/db.js");
const feedback = await import("../src/feedback.js");
const feedbackAsync = await import("../src/feedbackAsync.js");

const PG = { driver: "postgres", strict: true };
const handle = () => dbMod.sqliteHandle();
const UID = 900000008001;
const TABLES = ["users", "feedback", "feedback_outbox"];

// 把 `$n` 換成 `?`，並**依索引重排參數**（PG 的 `$n` 可以重複引用同一個參數，
// 例如 `VALUES (…, $6, $6)`；單純換成 `?` 會少一個佔位值）。
function translate(sql, params = []) {
  const order = [];
  const text = String(sql).replace(/\$(\d+)/g, (_m, n) => {
    order.push(Number(n) - 1);
    return "?";
  });
  return [text, order.map((i) => params[i])];
}

function worlds({ failOutbox = false } = {}) {
  const lite = handle();
  lite.prepare("DELETE FROM feedback WHERE user_id = ?").run(UID);
  lite.prepare("INSERT OR REPLACE INTO users(id, email, nickname, role, plan, created_at) VALUES (?,?,?,?,?,?)")
    .run(UID, "fb@example.test", "回饋王", "member", "free", "2026-01-01T00:00:00.000Z");

  const mem = new DatabaseSync(":memory:");
  const disk = new DatabaseSync(path.join(dataDir, "v3.db"), { readOnly: true });
  for (const table of TABLES) {
    const ddl = disk.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name=?").get(table);
    assert.ok(ddl?.sql, `必須抓到 ${table} 的 DDL`);
    mem.exec(ddl.sql);
  }
  disk.close();
  mem.prepare("INSERT INTO users(id, email, nickname, role, plan, created_at) VALUES (?,?,?,?,?,?)")
    .run(UID, "fb@example.test", "回饋王", "member", "free", "2026-01-01T00:00:00.000Z");
  if (failOutbox) {
    // outbox 一定失敗 ⇒ 交易必須回滾掉 feedback 那一句。
    mem.exec("CREATE TRIGGER boom BEFORE INSERT ON feedback_outbox BEGIN SELECT RAISE(ABORT, 'boom'); END");
  }

  // ⚠️ PG 的聚合（`COUNT(*)`）回來的是 **bigint 字串**，SQLite 回來的是數字。
  // 夾具要模擬 PG 的型別，否則「忘記轉數字」的變異永遠殺不死（實測存活過一次）。
  const asPgRow = (row) => (row && "n" in row ? { ...row, n: String(row.n) } : row);
  const runOn = (h, sql, params = []) => {
    const [text, ordered] = translate(sql, params);
    const stmt = h.prepare(text);
    if (/^\s*(select|with)/i.test(sql) || /returning/i.test(sql)) return stmt.all(...ordered).map(asPgRow);
    stmt.run(...ordered);
    return [];
  };
  // 有交易的假 driver：`query()` 走隱含交易（等同 PG 的行為），`withTransaction()` 才是真的包起來。
  const pgDriver = {
    // `ensureFeedbackStoreOnce()` 會用 `pgDriver.exec()` 送鏡射 DDL（CREATE TABLE IF NOT EXISTS）。
    // 夾具裡已經有那些表，而 `pgSchema` 產生的是 **PG 方言**（`BIGINT GENERATED BY DEFAULT AS IDENTITY`）
    // —— SQLite 跑不動是正常的，這裡直接當成 no-op（表已經在了）。
    async exec(sql) {
      try { mem.exec(String(sql)); } catch { /* 夾具已鏡射同樣的表 */ }
    },
    async query(sql, params = []) {
      const rows = runOn(mem, sql, params);
      return { rows, rowCount: rows.length };
    },
    async withTransaction(fn) {
      mem.exec("BEGIN");
      try {
        const client = {
          async query(sql, params = []) {
            const rows = runOn(mem, sql, params);
            return { rows, rowCount: rows.length };
          },
        };
        const out = await fn(client);
        mem.exec("COMMIT");
        return out;
      } catch (error) {
        try { mem.exec("ROLLBACK"); } catch { /* keep original */ }
        throw error;
      }
    },
  };
  const feedbackRows = () => mem.prepare("SELECT * FROM feedback ORDER BY id").all();
  const outboxRows = () => mem.prepare("SELECT * FROM feedback_outbox ORDER BY id").all();
  return [lite, mem, pgDriver, feedbackRows, outboxRows];
}

const INPUT = {
  kind: "bug",
  body: "搜尋結果的分頁偶爾會跳到第一頁",
  contact: "fb@example.test",
  // ⚠️ `normalizeFeedbackContext()` 只留白名單（route／view／role／version／q／filter…）——
  // `path` 不在裡面會被丢掉（第一版測試就是這樣紅的：payload.context.path 是 undefined）。
  context: { route: "/listings", version: "test-1" },
};

test("送出：PG 上一筆 feedback ＋ 一筆 outbox 事件，欄位與同步版逐欄相同", async () => {
  const [lite, , pgDriver, feedbackRows, outboxRows] = worlds();
  const out = await feedbackAsync.submitFeedbackAsync(UID, INPUT, { ...PG, pgDriver });
  assert.deepEqual(out, { ok: true, id: Number(feedbackRows()[0].id) });
  assert.equal(feedbackRows().length, 1, "PG 要有一筆 feedback");
  assert.equal(outboxRows().length, 1, "PG 要有一筆初始 outbox 事件（不變式）");
  const row = feedbackRows()[0];
  assert.equal(row.kind, "bug");
  assert.equal(row.body, INPUT.body);
  assert.equal(row.status, "new");
  assert.equal(row.user_id, UID);
  const payload = JSON.parse(outboxRows()[0].payload);
  assert.equal(payload.external_feedback_id, Number(row.id));
  assert.equal(payload.kind, "bug");
  assert.equal(payload.content, INPUT.body);
  assert.equal(payload.trust_level, "untrusted", "回饋內容是未信任輸入");
  assert.equal(payload.context.route, "/listings");
  assert.equal(payload.app_version, "test-1", "app_version 取自 context.version");
  // 與同步版逐欄比對（同一份輸入、另一個 store）
  const syncOut = feedback.createFeedbackWithOutbox(lite, UID, INPUT);
  const syncRow = lite.prepare("SELECT * FROM feedback WHERE user_id = ?").get(UID);
  const syncOutbox = lite.prepare("SELECT * FROM feedback_outbox ORDER BY id").all()[0];
  assert.equal(syncOut.id, syncRow.id);
  for (const key of ["kind", "body", "contact", "status", "admin_note"]) {
    assert.equal(row[key], syncRow[key], `${key} 必須與同步版相同`);
  }
  const syncPayload = JSON.parse(syncOutbox.payload);
  for (const key of ["kind", "content", "contact", "trust_level", "app_version"]) {
    assert.equal(payload[key], syncPayload[key], `payload.${key} 必須與同步版相同`);
  }
  assert.equal(outboxRows()[0].status, syncOutbox.status);
  assert.equal(outboxRows()[0].max_attempts, syncOutbox.max_attempts);
});

test("不變式：outbox 寫入失敗時，feedback 必須一起回滾（同一交易）", async () => {
  const [, , pgDriver, feedbackRows, outboxRows] = worlds({ failOutbox: true });
  await assert.rejects(
    () => feedbackAsync.submitFeedbackAsync(UID, INPUT, { ...PG, pgDriver }),
    /boom/,
  );
  assert.equal(feedbackRows().length, 0, "outbox 失敗時不得留下 feedback（否則 Ops 永遠不會知道這筆）");
  assert.equal(outboxRows().length, 0);
});

test("honeypot：什麼都不寫，而且回 ok（與同步版同義）", async () => {
  const [, , pgDriver, feedbackRows, outboxRows] = worlds();
  const out = await feedbackAsync.submitFeedbackAsync(UID, { ...INPUT, website: "http://spam" }, { ...PG, pgDriver });
  assert.deepEqual(out, { ok: true, id: 0 });
  assert.equal(feedbackRows().length, 0);
  assert.equal(outboxRows().length, 0);
});

test("內容驗證與洪水限制：訊息與同步版相同", async () => {
  const [lite, , pgDriver] = worlds();
  // 太短
  const shortSync = (() => { try { feedback.createFeedbackWithOutbox(lite, UID, { body: "太" }); return null; } catch (e) { return e; } })();
  const shortPg = await feedbackAsync.submitFeedbackAsync(UID, { body: "太" }, { ...PG, pgDriver }).then(() => null, (e) => e);
  assert.equal(shortPg?.status, 400);
  assert.equal(shortPg.message, shortSync.message, "太短的訊息必須相同");
  // 剛剛才送過 ⇒ 429
  await feedbackAsync.submitFeedbackAsync(UID, INPUT, { ...PG, pgDriver });
  const again = await feedbackAsync.submitFeedbackAsync(UID, INPUT, { ...PG, pgDriver }).then(() => null, (e) => e);
  // 對照組要在同一個狀態上跑：本機也要先有一筆剛送出的（否則同步版會成功，沒東西可比）。
  feedback.createFeedbackWithOutbox(lite, UID, INPUT);
  const againSync = (() => { try { feedback.createFeedbackWithOutbox(lite, UID, INPUT); return null; } catch (e) { return e; } })();
  assert.equal(again?.status, 429);
  assert.equal(again.message, againSync.message, "洪水限制的訊息必須相同");
  assert.match(again.message, /剛剛才送出/);
});

test("後台列表：篩選、排序與 email／nickname 的裝飾都與同步版相同", async () => {
  const [lite, mem, pgDriver] = worlds();
  // 兩邊各寫三筆（直接 INSERT，避開洪水限制）
  const seed = (h, id, kind, status, body) => h.prepare(
    `INSERT INTO feedback(id, user_id, kind, body, contact, context, status, admin_note, created_at, updated_at)
     VALUES (?,?,?,?,?,?,?,?,?,?)`,
  ).run(id, UID, kind, body, "", JSON.stringify({ path: "/x" }), status, "", "2026-09-01T00:00:00.000Z", "2026-09-01T00:00:00.000Z");
  for (const [id, kind, status] of [[8101, "bug", "new"], [8102, "idea", "done"], [8103, "other", "planned"]]) {
    seed(mem, id, kind, status, `內容 ${id}`);
    seed(lite, id, kind, status, `內容 ${id}`);
  }
  const viaPg = await feedbackAsync.listFeedbackAsync({}, { ...PG, pgDriver });
  const viaSync = feedback.listFeedback(lite, {});
  assert.deepEqual(viaPg, viaSync, "整包必須逐欄相同（含 email／nickname／context 的形狀）");
  assert.equal(viaPg.length, 3);
  assert.equal(viaPg[0].id, 8103, "預設由新到舊（id DESC）");
  assert.equal(viaPg[0].email, "fb@example.test", "email 要從 users join 出來");
  assert.equal(viaPg[0].nickname, "回饋王");
  assert.deepEqual(viaPg[0].context, { path: "/x" });
  for (const [query, expected] of [[{ status: "done" }, 1], [{ kind: "bug" }, 1], [{ status: "all", kind: "all" }, 3], [{ status: "nope" }, 3]]) {
    assert.deepEqual(
      await feedbackAsync.listFeedbackAsync(query, { ...PG, pgDriver }),
      feedback.listFeedback(lite, query),
      `篩選 ${JSON.stringify(query)} 必須與同步版相同`,
    );
    assert.equal((await feedbackAsync.listFeedbackAsync(query, { ...PG, pgDriver })).length, expected, `篩選 ${JSON.stringify(query)} 的筆數`);
  }
  assert.equal((await feedbackAsync.listFeedbackAsync({ limit: 2 }, { ...PG, pgDriver })).length, 2, "limit 要生效");
});

test("統計：狀態／類型白名單與 total 都相同（bigint 要轉數字）", async () => {
  const [lite, mem, pgDriver] = worlds();
  for (const [id, kind, status] of [[8201, "bug", "new"], [8202, "bug", "done"], [8203, "idea", "done"]]) {
    const insert = (h) => h.prepare(
      `INSERT INTO feedback(id, user_id, kind, body, contact, context, status, admin_note, created_at, updated_at)
       VALUES (?,?,?,?,?,?,?,?,?,?)`,
    ).run(id, UID, kind, `b${id}`, "", "{}", status, "", "2026-09-01T00:00:00.000Z", "2026-09-01T00:00:00.000Z");
    insert(mem);
    insert(lite);
  }
  const viaPg = await feedbackAsync.feedbackStatsAsync({ ...PG, pgDriver });
  const viaSync = feedback.feedbackStats(lite);
  assert.deepEqual(viaPg, viaSync, "統計必須逐欄相同");
  assert.equal(viaPg.total, 3);
  assert.equal(viaPg.byStatus.done, 2);
  assert.equal(viaPg.byKind.bug, 2);
  assert.equal(typeof viaPg.total, "number", "PG 的 COUNT 是字串，必須轉成數字");
});

test("改狀態／備註：只改帶到的欄位、404 與截斷都與同步版相同", async () => {
  const [lite, mem, pgDriver] = worlds();
  const insert = (h) => h.prepare(
    `INSERT INTO feedback(id, user_id, kind, body, contact, context, status, admin_note, created_at, updated_at)
     VALUES (?,?,?,?,?,?,?,?,?,?)`,
  ).run(8301, UID, "bug", "b", "", "{}", "new", "舊備註", "2026-09-01T00:00:00.000Z", "2026-09-01T00:00:00.000Z");
  insert(mem);
  insert(lite);
  const viaPg = await feedbackAsync.updateFeedbackAsync(8301, { status: "doing" }, { ...PG, pgDriver });
  const viaSync = feedback.updateFeedback(lite, 8301, { status: "doing" });
  // ⚠️ `updated_at` 是「當下時間」，兩次呼叫本來就會差幾毫秒 ⇒ 逐欄比對時要排除它，
  // 但要另外確認兩邊都真的把它更新了（否則等於沒驗到）。
  const stripStamp = (row) => ({ ...row, updated_at: undefined });
  assert.deepEqual(stripStamp(viaPg), stripStamp(viaSync), "回傳必須逐欄相同（updated_at 除外）");
  assert.notEqual(viaPg.updated_at, "2026-09-01T00:00:00.000Z", "updated_at 要更新");
  assert.notEqual(viaSync.updated_at, "2026-09-01T00:00:00.000Z");
  assert.equal(viaPg.status, "doing");
  assert.equal(viaPg.admin_note, "舊備註", "沒帶到的欄位要沿用");
  // 備註截斷（2000 字）
  const long = await feedbackAsync.updateFeedbackAsync(8301, { admin_note: "x".repeat(3000) }, { ...PG, pgDriver });
  assert.equal(long.admin_note.length, 2000);
  // 找不到 ⇒ 404，訊息相同
  const missingPg = await feedbackAsync.updateFeedbackAsync(999999, {}, { ...PG, pgDriver }).then(() => null, (e) => e);
  const missingSync = (() => { try { feedback.updateFeedback(lite, 999999, {}); return null; } catch (e) { return e; } })();
  assert.equal(missingPg?.status, 404);
  assert.equal(missingPg.message, missingSync.message);
  // 沒有可改的欄位 ⇒ 原樣回傳，而且**不得動 updated_at**。
  // ⚠️ 這裡不能拿本機那一份來 deepEqual：上面長備註只改了 PG，兩邊狀態已經不同
  // （第一版就是這樣紅的）。改成跟「上一次的 PG 結果」比。
  const noop = await feedbackAsync.updateFeedbackAsync(8301, {}, { ...PG, pgDriver });
  assert.equal(noop.admin_note.length, 2000, "原樣回傳（備註仍是剛才那串）");
  assert.equal(noop.updated_at, long.updated_at, "沒有可改的欄位時不得動 updated_at");
  assert.deepEqual(noop.context, {});
});

test("注入式 exec 的兩種形狀都要吃得下（裸陣列 vs { rows, rowCount }）", async () => {
  const [lite, mem, pgDriver] = worlds();
  const insert = (h) => h.prepare(
    `INSERT INTO feedback(id, user_id, kind, body, contact, context, status, admin_note, created_at, updated_at)
     VALUES (?,?,?,?,?,?,?,?,?,?)`,
  ).run(8401, UID, "bug", "b", "", "{}", "new", "", "2026-09-01T00:00:00.000Z", "2026-09-01T00:00:00.000Z");
  insert(mem);
  insert(lite);
  const bare = async (sql, params = []) => {
    const [text, ordered] = translate(sql, params);
    const stmt = mem.prepare(text);
    if (/^\s*(select|with)/i.test(sql) || /returning/i.test(sql)) return stmt.all(...ordered);
    stmt.run(...ordered);
    return [];
  };
  const wrapped = async (sql, params = []) => {
    const rows = await bare(sql, params);
    return { rows, rowCount: Number(rows.rowCount) || 0 };
  };
  assert.deepEqual(
    await feedbackAsync.listFeedbackAsync({}, { ...PG, exec: wrapped }),
    await feedbackAsync.listFeedbackAsync({}, { ...PG, exec: bare }),
    "兩種 exec 形狀的列表必須相同",
  );
  assert.deepEqual(
    await feedbackAsync.feedbackStatsAsync({ ...PG, exec: wrapped }),
    feedback.feedbackStats(lite),
    "兩種形狀的統計都要等於同步版",
  );
});

test("非 postgres：三個入口都走同步路徑（不碰傳入的 exec）", async () => {
  const [lite] = worlds();
  let calls = 0;
  const boom = async () => { calls += 1; throw new Error("exec 不該被呼叫（sqlite 模式）"); };
  const sqlite = { driver: "sqlite", exec: boom };
  const out = await feedbackAsync.submitFeedbackAsync(UID, INPUT, sqlite);
  assert.equal(out.ok, true);
  assert.ok(lite.prepare("SELECT COUNT(*) AS n FROM feedback WHERE user_id = ?").get(UID).n >= 1);
  const items = await feedbackAsync.listFeedbackAsync({}, sqlite);
  assert.deepEqual(items, feedback.listFeedback(lite, {}));
  assert.deepEqual(await feedbackAsync.feedbackStatsAsync(sqlite), feedback.feedbackStats(lite));
  assert.equal(calls, 0, "sqlite 模式不得呼叫 PG runner");
});
