// 刊登生產力工具（說明範本／聯絡人）的 **live PG** 驗證（2026-09-27）。
//
// 離線 parity 測試（listing-tools-async.test.js）證明「PG 分支與同步版落地同樣的位元組」，
// 但它用的 PG 替身是記憶體 SQLite。**只有真 PG 能證明三件事**：
//
//   1. `PG_SCHEMA_STATEMENTS`／`PG_ALTER_STATEMENTS` 真的是合法 PG 語法
//      （`GENERATED BY DEFAULT AS IDENTITY`、`ADD COLUMN IF NOT EXISTS` 都是 PG 專屬，
//      SQLite 替身根本測不到）。
//   2. 那個**部分唯一索引**（`... ON listing_contact_profile(user_id) WHERE is_account = 1`）
//      真的建得起來、而且真的擋得住第二筆帳號聯絡人。這是「一位使用者最多一筆帳號聯絡人」
//      的唯一保證；實測正式站這三張表**只有 pkey**（匯入時 indexes:false），索引不存在。
//   3. identity 序列在真的 INSERT（不指定 id）之後真的會前進——即 2026-09-27 那個
//      `admin_audit` 缺陷的同類風險不會在這裡重演。
//
// ⚠️ **安全設計（刻意照抄 reject-match-live-pg.test.js，不要簡化）**：
//   * 這支**不吃** `PG_TEST_URL`：本機的 `PG_TEST_URL` 指向的 `5151_shadow` **就是正式站**
//     （同 postmaster、同資料庫）。gate 在它上面，本機一跑就會建索引、寫資料進正式庫。
//   * 只認 `PG_LIVE_REPRO_URL`，且**資料庫名必須在允許清單內**（`5151_shadow` 一律拒絕）。
//   * 自己種的資料一律用遠離序列的極大 id，並在結束前刪掉。
//
// 用法（隔離環境，NAS 上的 prb-repro-pg）：
//   PG_LIVE_REPRO_URL='postgres://postgres:x@192.168.0.220:15434/repro' \
//     node --test v3/test/listing-tools-live-pg.test.js
import { test } from "node:test";
import assert from "node:assert/strict";

const RAW = String(process.env.PG_LIVE_REPRO_URL || "").trim();
// 只允許明確的隔離資料庫名。正式庫（5151_shadow）永遠不在此列。
const ALLOWED_DB = new Set(["repro", "tracker_test", "repro2"]);
const DB = (() => { try { return new URL(RAW).pathname.replace(/^\//, ""); } catch { return ""; } })();
const REFUSED = RAW && !ALLOWED_DB.has(DB);
const skip = !RAW ? "PG_LIVE_REPRO_URL 未設定（live PG 驗證需要隔離環境）"
  : REFUSED ? `拒絕執行：資料庫 "${DB}" 不在允許清單 ${[...ALLOWED_DB].join("/")}（正式庫 5151_shadow 一律拒絕）`
    : false;

// 自己種的資料用遠離序列的極大 id，不可能與真實資料相撞，也方便清理。
const UID = 900000000101;

test("live PG：schema bootstrap 可在真 PG 上執行，且部分唯一索引真的擋得住第二筆帳號聯絡人", { skip }, async () => {
  const { createPostgresDriver } = await import("../src/dbDriverPostgres.js");
  const asyncMod = await import("../src/listingToolsAsync.js");

  const pgDriver = await createPostgresDriver({ connectionString: RAW });
  const query = (sql, params = []) => pgDriver.query(sql, params).then((r) => r.rows);

  // 先確認真的連到預期的隔離庫（防止 URL 被改成正式站）。
  const who = (await query("SELECT current_database() AS db"))[0];
  assert.equal(who.db, DB, "連到的資料庫必須與 URL 一致");
  assert.ok(ALLOWED_DB.has(who.db), `拒絕在 ${who.db} 上執行`);

  const cleanup = async () => {
    await query("DELETE FROM listing_contact_profile WHERE user_id = $1", [UID]).catch(() => {});
    await query("DELETE FROM listing_description_template WHERE user_id = $1", [UID]).catch(() => {});
  };
  await cleanup(); // 上一次若死在種資料與清理之間，先清乾淨

  // 1) schema bootstrap（PG 專屬語法）真的跑得起來。
  await asyncMod.ensureListingToolsStoreOnce(pgDriver);

  // 2) 部分唯一索引存在——這是「一位使用者最多一筆帳號聯絡人」的唯一保證。
  const idx = await query(asyncMod.PG_ACCOUNT_INDEX_EXISTS_SQL, ["idx_listing_contact_one_account"]);
  assert.equal(idx.length, 1, "補建之後 must 找得到 idx_listing_contact_one_account");
  const def = await query(
    "SELECT indexdef FROM pg_indexes WHERE schemaname='public' AND indexname='idx_listing_contact_one_account'",
  );
  assert.match(def[0].indexdef, /UNIQUE/i, "必須是 UNIQUE");
  assert.match(def[0].indexdef, /WHERE.*is_account/i, "必須是**部分**索引（WHERE is_account = 1）");

  // 3) 索引真的擋得住第二筆：手動塞兩筆 is_account=1，第二筆必須違反唯一性。
  const ins = `INSERT INTO listing_contact_profile(user_id, label, contact_name, phone, line_url, is_account, created_at, updated_at)
               VALUES ($1,$2,$3,$4,$5,1,$6,$6) RETURNING id`;
  const stamp = "2026-06-01T00:00:00.000Z";
  const first = await query(ins, [UID, "帳號", "live", "0912345678", "", stamp]);
  assert.ok(first[0].id, "第一筆帳號聯絡人必須真的落地");
  await assert.rejects(
    () => query(ins, [UID, "帳號", "live", "0912345678", "", stamp]),
    /duplicate key|unique/i,
    "第二筆 is_account=1 必須被部分唯一索引擋下（擋不住就代表索引沒建起來）",
  );

  // 4) identity 序列真的會前進：連續兩筆不指定 id 的 INSERT 必須拿到不同 id
  //    （2026-09-27 的 admin_audit 缺陷就是序列落後 ⇒ 每筆 INSERT 都撞 pkey）。
  await query("DELETE FROM listing_description_template WHERE user_id = $1", [UID]);
  const t1 = await query(
    `INSERT INTO listing_description_template(user_id,name,body,sort_order,created_at,updated_at)
     VALUES ($1,'live-a','<p>a</p>',0,$2,$2) RETURNING id`, [UID, stamp]);
  const t2 = await query(
    `INSERT INTO listing_description_template(user_id,name,body,sort_order,created_at,updated_at)
     VALUES ($1,'live-b','<p>b</p>',1,$2,$2) RETURNING id`, [UID, stamp]);
  assert.ok(t1[0].id && t2[0].id, "兩筆範本都要落地");
  assert.notEqual(String(t1[0].id), String(t2[0].id), "identity 序列沒有前進（第二筆會撞主鍵）");

  await cleanup();
});

test("live PG：透過島嶼入口做的 CRUD 在真 PG 上可讀回，且清理乾淨", { skip }, async () => {
  const { createPostgresDriver } = await import("../src/dbDriverPostgres.js");
  const asyncMod = await import("../src/listingToolsAsync.js");

  const pgDriver = await createPostgresDriver({ connectionString: RAW });
  const query = (sql, params = []) => pgDriver.query(sql, params).then((r) => r.rows);
  await query("DELETE FROM listing_contact_profile WHERE user_id = $1", [UID]);
  await query("DELETE FROM listing_description_template WHERE user_id = $1", [UID]);

  const now = new Date("2026-06-01T00:00:00.000Z");
  const created = await asyncMod.createDescriptionTemplateAsync(
    UID, { name: "live 範本", body: "<p>live</p>" },
    { now, pgDriver, driver: "postgres", plan: "sponsor" },
  );
  assert.equal(created.name, "live 範本");
  assert.ok(created.id, "必須拿到 id（PG 走 RETURNING）");

  const listed = await asyncMod.listDescriptionTemplatesAsync(UID, { pgDriver, driver: "postgres" });
  assert.equal(listed.length, 1);
  assert.equal(listed[0].id, created.id, "讀回來的必須是剛寫進去那一筆");
  assert.equal(listed[0].body, created.body);

  // 不指定 id 直接讀 PG：證明資料真的在**資料庫**裡，不是只在回傳值裡。
  const raw = await query("SELECT name FROM listing_description_template WHERE id = $1", [created.id]);
  assert.equal(raw.length, 1, "PG 裡真的有一列");
  assert.equal(raw[0].name, "live 範本");

  const contacts = await asyncMod.listContactProfilesAsync(UID, { pgDriver, driver: "postgres" });
  assert.equal(contacts.length, 1, "第一次列出時應自動建立帳號聯絡人");
  assert.equal(contacts[0].is_account, true);
  assert.equal(contacts[0].locked, true);

  await query("DELETE FROM listing_contact_profile WHERE user_id = $1", [UID]);
  await query("DELETE FROM listing_description_template WHERE user_id = $1", [UID]);
  const left = await query("SELECT COUNT(*)::int AS n FROM listing_description_template WHERE user_id = $1", [UID]);
  assert.equal(left[0].n, 0, "測試資料必須清乾淨");
});
