// 會員照片素材庫的 **live PG** 驗證（2026-09-27）。
//
// 離線 parity（member-media-async.test.js）用的 PG 替身是記憶體 SQLite，它證明不了：
//
//   1. PG 專屬 DDL 真的合法（`GENERATED BY DEFAULT AS IDENTITY`、`ADD COLUMN IF NOT EXISTS`）。
//   2. **兩個唯一索引真的建得起來、真的擋得住**：`media_tags` 的表約束
//      `UNIQUE(user_id, name)` 是隱式索引，pgSchema 鏡射不到——實測正式站只有 pkey。
//      少了它，「同名標籤重用」與改名時的 409「已有同名標籤」都不會發生。
//   3. `CREATE UNIQUE INDEX` 之前**必須先清重複**：有重複時它會直接失敗，
//      整個 schema bootstrap 就掛掉。這裡刻意先種兩筆同名標籤，驗證 bootstrap 有活下來
//      而且把對應改指到保留者。
//
// ⚠️ 安全設計照抄 reject-match-live-pg.test.js：**不吃 `PG_TEST_URL`**（本機那個就是正式站），
// 只認 `PG_LIVE_REPRO_URL` 且資料庫名要在允許清單內；CI 的拋棄式 `tracker_test` 在清單內。
import { test } from "node:test";
import assert from "node:assert/strict";

const RAW = String(process.env.PG_LIVE_REPRO_URL || "").trim();
const ALLOWED_DB = new Set(["repro", "tracker_test", "repro2"]);
const DB = (() => { try { return new URL(RAW).pathname.replace(/^\//, ""); } catch { return ""; } })();
const REFUSED = RAW && !ALLOWED_DB.has(DB);
const skip = !RAW ? "PG_LIVE_REPRO_URL 未設定（live PG 驗證需要隔離環境）"
  : REFUSED ? `拒絕執行：資料庫 "${DB}" 不在允許清單 ${[...ALLOWED_DB].join("/")}（正式庫 5151_shadow 一律拒絕）`
    : false;

const UID = 900000000201;
const KEY = "c".repeat(32);

test("live PG：兩個唯一索引真的存在，而且擋得住重複的標籤名與 storage_key", { skip }, async () => {
  const { createPostgresDriver } = await import("../src/dbDriverPostgres.js");
  const asyncMod = await import("../src/memberMediaAsync.js");

  const pgDriver = await createPostgresDriver({ connectionString: RAW });
  const query = (sql, params = []) => pgDriver.query(sql, params).then((r) => r.rows);
  const who = (await query("SELECT current_database() AS db"))[0];
  assert.equal(who.db, DB, "連到的資料庫必須與 URL 一致");
  assert.ok(ALLOWED_DB.has(who.db), `拒絕在 ${who.db} 上執行`);

  const cleanup = async () => {
    await query("DELETE FROM media_tag_map WHERE media_id IN (SELECT id FROM member_media WHERE user_id=$1)", [UID]).catch(() => {});
    await query("DELETE FROM member_media WHERE user_id=$1", [UID]).catch(() => {});
    await query("DELETE FROM media_tags WHERE user_id=$1", [UID]).catch(() => {});
  };
  await cleanup();

  // 刻意先種兩筆同名標籤：bootstrap 必須先清重複才建得起唯一索引。
  const stamp = "2026-06-01T00:00:00.000Z";
  const t1 = await query("INSERT INTO media_tags(user_id,name,created_at) VALUES ($1,'重複',$2) RETURNING id", [UID, stamp]);
  const t2 = await query("INSERT INTO media_tags(user_id,name,created_at) VALUES ($1,'重複',$2) RETURNING id", [UID, stamp]);
  assert.ok(t1[0].id && t2[0].id, "兩筆同名標籤必須先種進去（否則這條測試沒有鑑別力）");

  // 種一張照片並把兩個同名標籤都掛上去，驗證 bootstrap 會把對應改指到保留者。
  const media = await query(
    `INSERT INTO member_media(user_id, storage_key, thumb_key, original_key, mime, format, watermarked, created_at)
     VALUES ($1,$2,$3,$4,'image/jpeg','jpeg',1,$5) RETURNING id`,
    [UID, `${KEY}.jpg`, `${KEY}_t.jpg`, `${KEY}_o.jpg`, stamp],
  );
  const mediaId = media[0].id;
  await query("INSERT INTO media_tag_map(media_id, tag_id) VALUES ($1,$2)", [mediaId, t1[0].id]);
  await query("INSERT INTO media_tag_map(media_id, tag_id) VALUES ($1,$2)", [mediaId, t2[0].id]);

  // 1) bootstrap 必須活下來（有重複時若先建索引，這裡就會直接炸）。
  await asyncMod.ensureMemberMediaStoreOnce(pgDriver);

  // 2) 兩個唯一索引都存在、且真的是 UNIQUE。
  for (const name of ["idx_member_media_key", "media_tags_user_name_key"]) {
    const def = await query("SELECT indexdef FROM pg_indexes WHERE schemaname='public' AND indexname=$1", [name]);
    assert.equal(def.length, 1, `${name} 必須存在（正式站沒有，是 bootstrap 補建的）`);
    assert.match(def[0].indexdef, /UNIQUE/i, `${name} 必須是 UNIQUE`);
  }

  // 3) 重複的標籤被清掉，而且使用者的分類沒有消失——對應被改指到保留者。
  const tags = await query("SELECT id, name FROM media_tags WHERE user_id=$1", [UID]);
  assert.equal(tags.length, 1, "同名標籤必須只剩一筆");
  const mapped = await query("SELECT tag_id FROM media_tag_map WHERE media_id=$1", [mediaId]);
  assert.equal(mapped.length, 1, "對應必須還在（改指到保留者），不能直接消失");
  assert.equal(String(mapped[0].tag_id), String(tags[0].id), "對應必須指向保留的那一筆");

  // 4) 索引真的擋得住第二筆同名標籤。
  await assert.rejects(
    () => query("INSERT INTO media_tags(user_id,name,created_at) VALUES ($1,'重複',$2)", [UID, stamp]),
    /duplicate key|unique/i,
    "第二筆同名標籤必須被唯一索引擋下",
  );

  // 5) 島嶼入口在真 PG 上跑得起來，而且讀得回剛種的資料。
  const listed = await asyncMod.listMemberMediaAsync(UID, { pgDriver, driver: "postgres" });
  assert.equal(listed.items.length, 1, "剛種的照片必須列出來");
  assert.equal(listed.items[0].tags.length, 1, "標籤必須跟著回來");
  assert.equal(listed.used, 1);

  await cleanup();
  const left = await query("SELECT COUNT(*)::int AS n FROM member_media WHERE user_id=$1", [UID]);
  assert.equal(left[0].n, 0, "測試資料必須清乾淨");
});
